# Type stub for the maturin-built _redis_rs Rust extension.
#
# These declarations exist only so type checkers know the names are
# importable. The full command surface comes from
# ``django_cachex.adapters.protocols.RespAdapterProtocol`` (and the
# ``RespPipelineProtocol`` / ``RespAsyncPipelineProtocol`` siblings),
# which the Python wrapper classes in ``django_cachex.adapters.redis_rs``
# mix into each Rust pyclass — the Rust class satisfies the protocol
# structurally, runtime-checkable.

from typing import Any

class RedisRsAwaitable:
    def __await__(self) -> Any: ...
    def cancel(self) -> bool: ...
    def cancelled(self) -> bool: ...
    def done(self) -> bool: ...
    def result(self) -> Any: ...
    def exception(self) -> Any: ...
    def add_done_callback(self, fn: Any, *, context: Any | None = None) -> None: ...
    def remove_done_callback(self, fn: Any) -> int: ...
    def get_loop(self) -> Any: ...

class RedisRsAdapter:
    # Constructor — connects in __init__. Rust-extension-specific extras
    # listed below; the full RespAdapterProtocol command surface is mixed
    # in by django_cachex.adapters.redis_rs.RedisRsAdapter.
    def __init__(self, servers: Any, **options: Any) -> None: ...
    def cache_statistics(self) -> tuple[int, int, int] | None: ...
    def close(self, **kwargs: Any) -> None: ...
    # Lock primitives — called from django_cachex.lock.
    def lock_acquire(self, key: str, token: str, timeout_ms: int | None = None) -> bool: ...
    def alock_acquire(self, key: str, token: str, timeout_ms: int | None = None) -> RedisRsAwaitable: ...
    def lock_release(self, key: str, token: str) -> int: ...
    def alock_release(self, key: str, token: str) -> RedisRsAwaitable: ...
    def lock_extend(self, key: str, token: str, additional_ms: int) -> int: ...
    def alock_extend(self, key: str, token: str, additional_ms: int) -> RedisRsAwaitable: ...
    # Pipeline execution — called from RedisRsPipelineAdapter.
    def pipeline_exec(self, commands: list[tuple[str, list[bytes]]], transaction: bool = False) -> Any: ...
    def apipeline_exec(
        self, commands: list[tuple[str, list[bytes]]], transaction: bool = False
    ) -> RedisRsAwaitable: ...

class RedisRsClusterAdapter(RedisRsAdapter): ...
class RedisRsSentinelAdapter(RedisRsAdapter): ...

class RedisRsPipelineAdapter:
    def __init__(self, adapter: RedisRsAdapter, *, transaction: bool = True) -> None: ...

class RedisRsAsyncPipelineAdapter(RedisRsPipelineAdapter): ...
