"""Adapter-layer Protocols.

These ``typing.Protocol`` classes formalize the contracts the cache and
pipeline layers rely on.

- :class:`RespPipelineProtocol`: sync pipeline-adapter contract.
- :class:`RespAsyncPipelineProtocol`: async pipeline-adapter contract.
  Identical to the sync one except ``execute()`` is awaitable; chainable
  methods stay sync because queueing never performs I/O.
- :class:`RespAdapterProtocol`: adapter contract; what
  :class:`~django_cachex.cache.resp.RespCache` calls on its
  underlying adapter. Concrete adapters
  (:class:`~django_cachex.adapters.valkey_py.ValkeyPyAdapter`,
  :class:`~django_cachex.adapters.redis_rs.RedisRsAdapter`,
  :class:`~django_cachex.adapters.valkey_glide.ValkeyGlideAdapter`)
  inherit from this Protocol so the contract is explicit at the class
  declaration; the inherited method bodies (``...``) are shadowed by each
  driver's real implementations.
"""

from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Iterator, Mapping, Sequence
    from datetime import datetime, timedelta

    from django_cachex.stampede import StampedeConfig
    from django_cachex.types import KeyType

# Aliases for builtins shadowed by `set`/`type` methods (PEP 649 defers
# annotations at runtime, but type checkers still resolve them in class scope).
_set = set


class _RespPipelineCommandsProtocol(Protocol):
    """Shared chainable-command surface for sync/async pipeline protocols.

    Internal: concrete adapters inherit from :class:`RespPipelineProtocol`
    or :class:`RespAsyncPipelineProtocol` (both extend this base) and
    implement the chainable methods against their underlying pipeline /
    batch object. Queueing is sync regardless of whether ``execute()`` is
    sync or async, so both protocols share the chainable surface here and
    differ only in ``execute()``'s return type.
    """

    # -------------------------------------------------------------------------
    # Core lifecycle (excluding ``execute()``, declared on the sub-protocols)
    # -------------------------------------------------------------------------

    def reset(self) -> None: ...
    # ``execute_command`` is a raw-command passthrough (used for EVAL etc.);
    # args may be any wire-encodable value, so the typing stays open.
    def execute_command(self, *args: Any) -> Any: ...

    # -------------------------------------------------------------------------
    # Strings / generic key ops
    #
    # Keys reaching the pipeline adapter are always already-prefixed ``str``
    # (``Pipeline._make_key`` returns ``str``); values are already-encoded
    # ``bytes | int`` (``Pipeline._encode`` return type). Mirrors the
    # ``RespAdapterProtocol`` parameter conventions.
    # -------------------------------------------------------------------------

    def set(
        self,
        key: str,
        value: bytes | int,
        *,
        ex: int | timedelta | None = None,
        px: int | timedelta | None = None,
        nx: bool = False,
        xx: bool = False,
        exat: int | datetime | None = None,
        pxat: int | datetime | None = None,
        keepttl: bool = False,
        get: bool = False,
    ) -> Any: ...
    def get(self, key: str) -> Any: ...
    def delete(self, *keys: str) -> Any: ...
    def exists(self, *keys: str) -> Any: ...
    def expire(self, key: str, seconds: int | timedelta) -> Any: ...
    def expireat(self, key: str, when: int | datetime) -> Any: ...
    def pexpire(self, key: str, milliseconds: int | timedelta) -> Any: ...
    def pexpireat(self, key: str, when: int | datetime) -> Any: ...
    def persist(self, key: str) -> Any: ...
    def ttl(self, key: str) -> Any: ...
    def pttl(self, key: str) -> Any: ...
    def expiretime(self, key: str) -> Any: ...
    def type(self, key: str) -> Any: ...
    def rename(self, src: str, dst: str) -> Any: ...
    def renamenx(self, src: str, dst: str) -> Any: ...
    def incrby(self, key: str, amount: int) -> Any: ...
    def decrby(self, key: str, amount: int) -> Any: ...

    # -------------------------------------------------------------------------
    # Lists
    # -------------------------------------------------------------------------

    def lpush(self, key: str, *values: bytes | int) -> Any: ...
    def rpush(self, key: str, *values: bytes | int) -> Any: ...
    def lpop(self, key: str, count: int | None = None) -> Any: ...
    def rpop(self, key: str, count: int | None = None) -> Any: ...
    def lrange(self, key: str, start: int, end: int) -> Any: ...
    def lindex(self, key: str, index: int) -> Any: ...
    def llen(self, key: str) -> Any: ...
    def lrem(self, key: str, count: int, value: bytes | int) -> Any: ...
    def ltrim(self, key: str, start: int, end: int) -> Any: ...
    def lset(self, key: str, index: int, value: bytes | int) -> Any: ...
    def linsert(self, key: str, where: str, pivot: bytes | int, value: bytes | int) -> Any: ...
    def lpos(
        self,
        key: str,
        value: bytes | int,
        rank: int | None = None,
        count: int | None = None,
        maxlen: int | None = None,
    ) -> Any: ...
    def lmove(self, src: str, dst: str, wherefrom: str = "LEFT", whereto: str = "RIGHT") -> Any: ...

    # -------------------------------------------------------------------------
    # Sets
    # -------------------------------------------------------------------------

    def sadd(self, key: str, *members: bytes | int) -> Any: ...
    def srem(self, key: str, *members: bytes | int) -> Any: ...
    def scard(self, key: str) -> Any: ...
    def sismember(self, key: str, member: bytes | int) -> Any: ...
    def smismember(self, key: str, *members: bytes | int) -> Any: ...
    def smembers(self, key: str) -> Any: ...
    def smove(self, src: str, dst: str, member: bytes | int) -> Any: ...
    def spop(self, key: str, count: int | None = None) -> Any: ...
    def srandmember(self, key: str, count: int | None = None) -> Any: ...
    def sdiff(self, *keys: str) -> Any: ...
    def sinter(self, *keys: str) -> Any: ...
    def sunion(self, *keys: str) -> Any: ...
    def sdiffstore(self, dst: str, *keys: str) -> Any: ...
    def sinterstore(self, dst: str, *keys: str) -> Any: ...
    def sunionstore(self, dst: str, *keys: str) -> Any: ...

    # -------------------------------------------------------------------------
    # Hashes
    #
    # Hash fields are passed through unencoded (the wrapper never encodes
    # them), so they're typed as ``str``. Values are encoded.
    # -------------------------------------------------------------------------

    def hset(
        self,
        key: str,
        field: str | None = None,
        value: bytes | int | None = None,
        mapping: Mapping[str, bytes | int] | None = None,
        items: list[Any] | None = None,
    ) -> Any: ...
    def hsetnx(self, key: str, field: str, value: bytes | int) -> Any: ...
    def hdel(self, key: str, *fields: str) -> Any: ...
    def hget(self, key: str, field: str) -> Any: ...
    def hgetall(self, key: str) -> Any: ...
    def hmget(self, key: str, *fields: str) -> Any: ...
    def hlen(self, key: str) -> Any: ...
    def hkeys(self, key: str) -> Any: ...
    def hvals(self, key: str) -> Any: ...
    def hexists(self, key: str, field: str) -> Any: ...
    def hincrby(self, key: str, field: str, amount: int = 1) -> Any: ...
    def hincrbyfloat(self, key: str, field: str, amount: float = 1.0) -> Any: ...

    # -------------------------------------------------------------------------
    # Sorted sets
    #
    # Score-range bounds accept ``float | str`` to allow the
    # ``"(<n>" / "-inf" / "+inf"`` literals Redis exposes.
    # -------------------------------------------------------------------------

    def zadd(
        self,
        key: str,
        mapping: Mapping[bytes | int, float],
        *,
        nx: bool = False,
        xx: bool = False,
        ch: bool = False,
        incr: bool = False,
        gt: bool = False,
        lt: bool = False,
    ) -> Any: ...
    def zcard(self, key: str) -> Any: ...
    def zscore(self, key: str, member: bytes | int) -> Any: ...
    def zmscore(self, key: str, members: Sequence[bytes | int]) -> Any: ...
    def zrank(self, key: str, member: bytes | int) -> Any: ...
    def zrevrank(self, key: str, member: bytes | int) -> Any: ...
    def zincrby(self, key: str, amount: float, member: bytes | int) -> Any: ...
    def zcount(self, key: str, min: float | str, max: float | str) -> Any: ...
    def zrem(self, key: str, *members: bytes | int) -> Any: ...
    def zremrangebyrank(self, key: str, start: int, end: int) -> Any: ...
    def zremrangebyscore(self, key: str, min: float | str, max: float | str) -> Any: ...
    def zpopmin(self, key: str, count: int | None = None) -> Any: ...
    def zpopmax(self, key: str, count: int | None = None) -> Any: ...
    def zrange(
        self,
        key: str,
        start: int,
        end: int,
        *,
        desc: bool = False,
        withscores: bool = False,
    ) -> Any: ...
    def zrevrange(
        self,
        key: str,
        start: int,
        end: int,
        *,
        withscores: bool = False,
    ) -> Any: ...
    def zrangebyscore(
        self,
        key: str,
        min: float | str,
        max: float | str,
        start: int | None = None,
        num: int | None = None,
        *,
        withscores: bool = False,
    ) -> Any: ...
    def zrevrangebyscore(
        self,
        key: str,
        max: float | str,
        min: float | str,
        start: int | None = None,
        num: int | None = None,
        *,
        withscores: bool = False,
    ) -> Any: ...

    # -------------------------------------------------------------------------
    # Streams
    #
    # Stream IDs, group names, and consumer names are always wire-level
    # ``str``; field names in XADD payloads are ``str`` and field values
    # are encoded ``bytes | int``.
    # -------------------------------------------------------------------------

    def xadd(
        self,
        key: str,
        fields: Mapping[str, bytes | int],
        *,
        id: str = "*",
        maxlen: int | None = None,
        approximate: bool = True,
        nomkstream: bool = False,
        minid: str | None = None,
        limit: int | None = None,
    ) -> Any: ...
    def xlen(self, key: str) -> Any: ...
    def xrange(self, key: str, min: str = "-", max: str = "+", count: int | None = None) -> Any: ...
    def xrevrange(self, key: str, max: str = "+", min: str = "-", count: int | None = None) -> Any: ...
    def xread(
        self,
        streams: Mapping[str, str],
        count: int | None = None,
        block: int | None = None,
    ) -> Any: ...
    def xreadgroup(
        self,
        group: str,
        consumer: str,
        streams: Mapping[str, str],
        count: int | None = None,
        block: int | None = None,
        noack: bool = False,
    ) -> Any: ...
    def xtrim(
        self,
        key: str,
        maxlen: int | None = None,
        approximate: bool = True,
        minid: str | None = None,
        limit: int | None = None,
    ) -> Any: ...
    def xdel(self, key: str, *entry_ids: str) -> Any: ...
    def xinfo_stream(self, key: str, full: bool = False) -> Any: ...
    def xinfo_groups(self, key: str) -> Any: ...
    def xinfo_consumers(self, key: str, group: str) -> Any: ...
    def xgroup_create(
        self,
        key: str,
        group: str,
        id: str = "$",
        *,
        mkstream: bool = False,
        entries_read: int | None = None,
    ) -> Any: ...
    def xgroup_destroy(self, key: str, group: str) -> Any: ...
    def xgroup_setid(self, key: str, group: str, id: str, *, entries_read: int | None = None) -> Any: ...
    def xgroup_delconsumer(self, key: str, group: str, consumer: str) -> Any: ...
    def xack(self, key: str, group: str, *entry_ids: str) -> Any: ...
    def xpending(self, key: str, group: str) -> Any: ...
    def xpending_range(
        self,
        key: str,
        group: str,
        *,
        min: str,
        max: str,
        count: int,
        consumername: str | None = None,
        idle: int | None = None,
    ) -> Any: ...
    def xclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        message_ids: list[str],
        idle: int | None = None,
        time: int | None = None,
        retrycount: int | None = None,
        force: bool = False,
        justid: bool = False,
    ) -> Any: ...
    def xautoclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        start_id: str = "0-0",
        count: int | None = None,
        justid: bool = False,
    ) -> Any: ...


@runtime_checkable
class RespPipelineProtocol(_RespPipelineCommandsProtocol, Protocol):
    """Sync pipeline-adapter contract: every command the sync ``Pipeline`` wrapper queues.

    Concrete adapters (one per driver) inherit from this Protocol and
    spell out the chainable surface (via :class:`_RespPipelineCommandsProtocol`)
    against their underlying pipeline / batch object. The :class:`Pipeline`
    wrapper queues ops on a concrete instance and decodes the raw results
    in ``execute()``.
    """

    def execute(self) -> list[Any]: ...


@runtime_checkable
class RespAsyncPipelineProtocol(_RespPipelineCommandsProtocol, Protocol):
    """Async pipeline-adapter contract; async sibling of :class:`RespPipelineProtocol`.

    Identical chainable surface; ``execute()`` and ``reset()`` are awaitable
    because some async drivers (``redis.asyncio.Pipeline``) implement them as
    coroutines. Chainable methods stay sync because queueing never performs I/O.
    """

    async def execute(self) -> list[Any]: ...
    async def reset(self) -> None: ...  # type: ignore[override]


@runtime_checkable
class RespAdapterProtocol(Protocol):
    """Wire-level adapter contract: every command + topology hook the cache calls.

    Concrete adapters inherit from this Protocol so the full ~200-method
    surface is declared in one place. Adapter implementations override
    every method; the ``...`` bodies inherited from this Protocol are
    therefore shadowed and never executed at runtime.
    """

    def __init__(self, servers: list[str], **options: Any) -> None: ...

    # Private-ish stampede helpers, called by ``RespCache`` to resolve
    # per-call overrides against the adapter's instance config.
    def resolve_stampede(self, stampede_prevention: bool | StampedeConfig | None = None) -> Any: ...
    def get_timeout_with_buffer(
        self,
        timeout: int | None,
        stampede_prevention: bool | StampedeConfig | None = None,
    ) -> int | None: ...

    def get_client(self, key: str | None = None, *, write: bool = False) -> Any: ...
    async def get_async_client(self, key: str | None = None, *, write: bool = False) -> Any: ...
    def add(
        self,
        key: str,
        value: bytes | int,
        timeout: int | None,
        *,
        stampede_prevention: bool | StampedeConfig | None = None,
    ) -> bool: ...
    async def aadd(
        self,
        key: str,
        value: bytes | int,
        timeout: int | None,
        *,
        stampede_prevention: bool | StampedeConfig | None = None,
    ) -> bool: ...
    def get(self, key: str, *, stampede_prevention: bool | StampedeConfig | None = None) -> bytes | None: ...
    async def aget(self, key: str, *, stampede_prevention: bool | StampedeConfig | None = None) -> bytes | None: ...
    def set(
        self,
        key: str,
        value: bytes | int,
        timeout: int | None,
        *,
        stampede_prevention: bool | StampedeConfig | None = None,
    ) -> None: ...
    async def aset(
        self,
        key: str,
        value: bytes | int,
        timeout: int | None,
        *,
        stampede_prevention: bool | StampedeConfig | None = None,
    ) -> None: ...
    def set_with_flags(
        self,
        key: str,
        value: bytes | int,
        timeout: int | None,
        *,
        nx: bool = False,
        xx: bool = False,
        get: bool = False,
        stampede_prevention: bool | StampedeConfig | None = None,
    ) -> bool | bytes | None: ...
    async def aset_with_flags(
        self,
        key: str,
        value: bytes | int,
        timeout: int | None,
        *,
        nx: bool = False,
        xx: bool = False,
        get: bool = False,
        stampede_prevention: bool | StampedeConfig | None = None,
    ) -> bool | bytes | None: ...
    def touch(self, key: str, timeout: int | None) -> bool: ...
    async def atouch(self, key: str, timeout: int | None) -> bool: ...
    def delete(self, key: str) -> bool: ...
    async def adelete(self, key: str) -> bool: ...
    def get_many(
        self,
        keys: list[str],
        *,
        stampede_prevention: bool | StampedeConfig | None = None,
    ) -> dict[str, bytes]: ...
    async def aget_many(
        self,
        keys: list[str],
        *,
        stampede_prevention: bool | StampedeConfig | None = None,
    ) -> dict[str, bytes]: ...
    def has_key(self, key: str) -> bool: ...
    async def ahas_key(self, key: str) -> bool: ...
    def type(self, key: str) -> KeyType | None: ...
    async def atype(self, key: str) -> KeyType | None: ...
    def incr(self, key: str, delta: int = 1) -> int: ...
    async def aincr(self, key: str, delta: int = 1) -> int: ...
    def set_many(
        self,
        data: Mapping[str, bytes | int],
        timeout: int | None,
        *,
        stampede_prevention: bool | StampedeConfig | None = None,
    ) -> list: ...
    async def aset_many(
        self,
        data: Mapping[str, bytes | int],
        timeout: int | None,
        *,
        stampede_prevention: bool | StampedeConfig | None = None,
    ) -> list: ...
    def delete_many(self, keys: Sequence[str]) -> int: ...
    async def adelete_many(self, keys: Sequence[str]) -> int: ...
    def clear(self) -> bool: ...
    async def aclear(self) -> bool: ...
    def close(self, **kwargs: Any) -> None: ...
    async def aclose(self, **kwargs: Any) -> None: ...
    def ttl(self, key: str) -> int | None: ...
    def pttl(self, key: str) -> int | None: ...
    def expiretime(self, key: str) -> int | None: ...
    def expire(self, key: str, timeout: int | timedelta) -> bool: ...
    def pexpire(self, key: str, timeout: int | timedelta) -> bool: ...
    def expireat(self, key: str, when: int | datetime) -> bool: ...
    def pexpireat(self, key: str, when: int | datetime) -> bool: ...
    def persist(self, key: str) -> bool: ...
    async def attl(self, key: str) -> int | None: ...
    async def apttl(self, key: str) -> int | None: ...
    async def aexpiretime(self, key: str) -> int | None: ...
    async def aexpire(self, key: str, timeout: int | timedelta) -> bool: ...
    async def apexpire(self, key: str, timeout: int | timedelta) -> bool: ...
    async def aexpireat(self, key: str, when: int | datetime) -> bool: ...
    async def apexpireat(self, key: str, when: int | datetime) -> bool: ...
    async def apersist(self, key: str) -> bool: ...
    def keys(self, pattern: str) -> list[str]: ...
    def iter_keys(self, pattern: str, itersize: int | None = None) -> Iterator[str]: ...
    def scan(
        self,
        cursor: int = 0,
        match: str | None = None,
        count: int | None = None,
        _type: str | None = None,
    ) -> tuple[int, list[str]]: ...
    async def ascan(
        self,
        cursor: int = 0,
        match: str | None = None,
        count: int | None = None,
        _type: str | None = None,
    ) -> tuple[int, list[str]]: ...
    def delete_pattern(self, pattern: str, itersize: int | None = None) -> int: ...
    def rename(self, src: str, dst: str) -> bool: ...
    def renamenx(self, src: str, dst: str) -> bool: ...
    async def akeys(self, pattern: str) -> list[str]: ...
    # Async generator: declared with plain ``def`` (not ``async def``) so async
    # generator overrides have a compatible signature; mypy types
    # ``async def -> AsyncIterator[X]`` as ``Coroutine[..., AsyncIterator[X]]``.
    def aiter_keys(self, pattern: str, itersize: int | None = None) -> AsyncIterator[str]: ...
    async def adelete_pattern(self, pattern: str, itersize: int | None = None) -> int: ...
    async def arename(self, src: str, dst: str) -> bool: ...
    async def arenamenx(self, src: str, dst: str) -> bool: ...
    def lock(
        self,
        key: str,
        timeout: float | None = None,
        sleep: float = 0.1,
        *,
        blocking: bool = True,
        blocking_timeout: float | None = None,
        thread_local: bool = True,
    ) -> Any: ...
    async def alock(
        self,
        key: str,
        timeout: float | None = None,
        sleep: float = 0.1,
        *,
        blocking: bool = True,
        blocking_timeout: float | None = None,
        thread_local: bool = True,
    ) -> Any: ...
    def pipeline(self, *, transaction: bool = True) -> RespPipelineProtocol: ...
    async def apipeline(self, *, transaction: bool = True) -> RespAsyncPipelineProtocol: ...
    def info(self, section: str | None = None) -> dict[str, Any]: ...
    def slowlog_get(self, count: int = 10) -> list[dict[str, Any]]: ...
    def slowlog_len(self) -> int: ...
    def hset(
        self,
        key: str,
        field: str | None = None,
        value: bytes | int | None = None,
        mapping: Mapping[str, bytes | int] | None = None,
        items: list[Any] | None = None,
    ) -> int: ...
    def hsetnx(self, key: str, field: str, value: bytes | int) -> bool: ...
    def hget(self, key: str, field: str) -> bytes | None: ...
    def hmget(self, key: str, *fields: str) -> list[bytes | None]: ...
    def hgetall(self, key: str) -> dict[str, bytes]: ...
    def hdel(self, key: str, *fields: str) -> int: ...
    def hexists(self, key: str, field: str) -> bool: ...
    def hlen(self, key: str) -> int: ...
    def hkeys(self, key: str) -> list[str]: ...
    def hvals(self, key: str) -> list[bytes]: ...
    def hincrby(self, key: str, field: str, amount: int = 1) -> int: ...
    def hincrbyfloat(self, key: str, field: str, amount: float = 1.0) -> float: ...
    async def ahset(
        self,
        key: str,
        field: str | None = None,
        value: bytes | int | None = None,
        mapping: Mapping[str, bytes | int] | None = None,
        items: list[Any] | None = None,
    ) -> int: ...
    async def ahsetnx(self, key: str, field: str, value: bytes | int) -> bool: ...
    async def ahget(self, key: str, field: str) -> bytes | None: ...
    async def ahmget(self, key: str, *fields: str) -> list[bytes | None]: ...
    async def ahgetall(self, key: str) -> dict[str, bytes]: ...
    async def ahdel(self, key: str, *fields: str) -> int: ...
    async def ahexists(self, key: str, field: str) -> bool: ...
    async def ahlen(self, key: str) -> int: ...
    async def ahkeys(self, key: str) -> list[str]: ...
    async def ahvals(self, key: str) -> list[bytes]: ...
    async def ahincrby(self, key: str, field: str, amount: int = 1) -> int: ...
    async def ahincrbyfloat(self, key: str, field: str, amount: float = 1.0) -> float: ...
    def lpush(self, key: str, *values: bytes | int) -> int: ...
    def rpush(self, key: str, *values: bytes | int) -> int: ...
    def lpop(self, key: str, count: int | None = None) -> bytes | list[bytes] | None: ...
    def rpop(self, key: str, count: int | None = None) -> bytes | list[bytes] | None: ...
    def llen(self, key: str) -> int: ...
    def lpos(
        self,
        key: str,
        value: bytes | int,
        rank: int | None = None,
        count: int | None = None,
        maxlen: int | None = None,
    ) -> int | list[int] | None: ...
    def lmove(self, src: str, dst: str, wherefrom: str, whereto: str) -> bytes | None: ...
    def lrange(self, key: str, start: int, end: int) -> list[bytes]: ...
    def lindex(self, key: str, index: int) -> bytes | None: ...
    def lset(self, key: str, index: int, value: bytes | int) -> bool: ...
    def lrem(self, key: str, count: int, value: bytes | int) -> int: ...
    def ltrim(self, key: str, start: int, end: int) -> bool: ...
    def linsert(self, key: str, where: str, pivot: bytes | int, value: bytes | int) -> int: ...
    def blpop(self, keys: list[str], timeout: float = 0) -> tuple[str, bytes] | None: ...
    def brpop(self, keys: list[str], timeout: float = 0) -> tuple[str, bytes] | None: ...
    def blmove(
        self,
        src: str,
        dst: str,
        timeout: float,
        wherefrom: str = "LEFT",
        whereto: str = "RIGHT",
    ) -> bytes | None: ...
    async def alpush(self, key: str, *values: bytes | int) -> int: ...
    async def arpush(self, key: str, *values: bytes | int) -> int: ...
    async def alpop(self, key: str, count: int | None = None) -> bytes | list[bytes] | None: ...
    async def arpop(self, key: str, count: int | None = None) -> bytes | list[bytes] | None: ...
    async def allen(self, key: str) -> int: ...
    async def alpos(
        self,
        key: str,
        value: bytes | int,
        rank: int | None = None,
        count: int | None = None,
        maxlen: int | None = None,
    ) -> int | list[int] | None: ...
    async def almove(self, src: str, dst: str, wherefrom: str, whereto: str) -> bytes | None: ...
    async def alrange(self, key: str, start: int, end: int) -> list[bytes]: ...
    async def alindex(self, key: str, index: int) -> bytes | None: ...
    async def alset(self, key: str, index: int, value: bytes | int) -> bool: ...
    async def alrem(self, key: str, count: int, value: bytes | int) -> int: ...
    async def altrim(self, key: str, start: int, end: int) -> bool: ...
    async def alinsert(self, key: str, where: str, pivot: bytes | int, value: bytes | int) -> int: ...
    async def ablpop(self, keys: list[str], timeout: float = 0) -> tuple[str, bytes] | None: ...
    async def abrpop(self, keys: list[str], timeout: float = 0) -> tuple[str, bytes] | None: ...
    async def ablmove(
        self,
        src: str,
        dst: str,
        timeout: float,
        wherefrom: str = "LEFT",
        whereto: str = "RIGHT",
    ) -> bytes | None: ...
    def sadd(self, key: str, *members: bytes | int) -> int: ...
    def srem(self, key: str, *members: bytes | int) -> int: ...
    def smembers(self, key: str) -> _set[bytes]: ...
    def sismember(self, key: str, member: bytes | int) -> bool: ...
    def scard(self, key: str) -> int: ...
    def spop(self, key: str, count: int | None = None) -> bytes | list[bytes] | None: ...
    def srandmember(self, key: str, count: int | None = None) -> bytes | list[bytes] | None: ...
    def smove(self, src: str, dst: str, member: bytes | int) -> bool: ...
    def sdiff(self, keys: list[str]) -> _set[bytes]: ...
    def sdiffstore(self, dest: str, keys: list[str]) -> int: ...
    def sinter(self, keys: list[str]) -> _set[bytes]: ...
    def sinterstore(self, dest: str, keys: list[str]) -> int: ...
    def sunion(self, keys: list[str]) -> _set[bytes]: ...
    def sunionstore(self, dest: str, keys: list[str]) -> int: ...
    def smismember(self, key: str, *members: bytes | int) -> list[bool]: ...
    def sscan(
        self,
        key: str,
        cursor: int = 0,
        match: str | None = None,
        count: int | None = None,
    ) -> tuple[int, _set[bytes]]: ...
    def sscan_iter(self, key: str, match: str | None = None, count: int | None = None) -> Iterator[bytes]: ...
    async def asadd(self, key: str, *members: bytes | int) -> int: ...
    async def asrem(self, key: str, *members: bytes | int) -> int: ...
    async def asmembers(self, key: str) -> _set[bytes]: ...
    async def asismember(self, key: str, member: bytes | int) -> bool: ...
    async def ascard(self, key: str) -> int: ...
    async def aspop(self, key: str, count: int | None = None) -> bytes | list[bytes] | None: ...
    async def asrandmember(self, key: str, count: int | None = None) -> bytes | list[bytes] | None: ...
    async def asmove(self, src: str, dst: str, member: bytes | int) -> bool: ...
    async def asdiff(self, keys: list[str]) -> _set[bytes]: ...
    async def asdiffstore(self, dest: str, keys: list[str]) -> int: ...
    async def asinter(self, keys: list[str]) -> _set[bytes]: ...
    async def asinterstore(self, dest: str, keys: list[str]) -> int: ...
    async def asunion(self, keys: list[str]) -> _set[bytes]: ...
    async def asunionstore(self, dest: str, keys: list[str]) -> int: ...
    async def asmismember(self, key: str, *members: bytes | int) -> list[bool]: ...
    async def asscan(
        self,
        key: str,
        cursor: int = 0,
        match: str | None = None,
        count: int | None = None,
    ) -> tuple[int, _set[bytes]]: ...
    def asscan_iter(  # async generator: see note on ``aiter_keys`` for ``def`` (not ``async def``)
        self,
        key: str,
        match: str | None = None,
        count: int | None = None,
    ) -> AsyncIterator[bytes]: ...
    def zadd(
        self,
        key: str,
        mapping: Mapping[bytes | int, float],
        *,
        nx: bool = False,
        xx: bool = False,
        gt: bool = False,
        lt: bool = False,
        ch: bool = False,
    ) -> int: ...
    def zrem(self, key: str, *members: bytes | int) -> int: ...
    def zscore(self, key: str, member: bytes | int) -> float | None: ...
    def zrank(self, key: str, member: bytes | int) -> int | None: ...
    def zrevrank(self, key: str, member: bytes | int) -> int | None: ...
    def zcard(self, key: str) -> int: ...
    def zcount(self, key: str, min_score: float | str, max_score: float | str) -> int: ...
    def zincrby(self, key: str, amount: float, member: bytes | int) -> float: ...
    def zrange(
        self,
        key: str,
        start: int,
        end: int,
        *,
        withscores: bool = False,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    def zrevrange(
        self,
        key: str,
        start: int,
        end: int,
        *,
        withscores: bool = False,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    def zrangebyscore(
        self,
        key: str,
        min_score: float | str,
        max_score: float | str,
        *,
        start: int | None = None,
        num: int | None = None,
        withscores: bool = False,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    def zrevrangebyscore(
        self,
        key: str,
        max_score: float | str,
        min_score: float | str,
        *,
        start: int | None = None,
        num: int | None = None,
        withscores: bool = False,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    def zremrangebyrank(self, key: str, start: int, end: int) -> int: ...
    def zremrangebyscore(self, key: str, min_score: float | str, max_score: float | str) -> int: ...
    def zpopmin(self, key: str, count: int | None = None) -> list[tuple[bytes, float]]: ...
    def zpopmax(self, key: str, count: int | None = None) -> list[tuple[bytes, float]]: ...
    def zmscore(self, key: str, *members: bytes | int) -> list[float | None]: ...
    async def azadd(
        self,
        key: str,
        mapping: Mapping[bytes | int, float],
        *,
        nx: bool = False,
        xx: bool = False,
        gt: bool = False,
        lt: bool = False,
        ch: bool = False,
    ) -> int: ...
    async def azrem(self, key: str, *members: bytes | int) -> int: ...
    async def azscore(self, key: str, member: bytes | int) -> float | None: ...
    async def azrank(self, key: str, member: bytes | int) -> int | None: ...
    async def azrevrank(self, key: str, member: bytes | int) -> int | None: ...
    async def azcard(self, key: str) -> int: ...
    async def azcount(self, key: str, min_score: float | str, max_score: float | str) -> int: ...
    async def azincrby(self, key: str, amount: float, member: bytes | int) -> float: ...
    async def azrange(
        self,
        key: str,
        start: int,
        end: int,
        *,
        withscores: bool = False,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    async def azrevrange(
        self,
        key: str,
        start: int,
        end: int,
        *,
        withscores: bool = False,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    async def azrangebyscore(
        self,
        key: str,
        min_score: float | str,
        max_score: float | str,
        *,
        start: int | None = None,
        num: int | None = None,
        withscores: bool = False,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    async def azrevrangebyscore(
        self,
        key: str,
        max_score: float | str,
        min_score: float | str,
        *,
        start: int | None = None,
        num: int | None = None,
        withscores: bool = False,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    async def azremrangebyrank(self, key: str, start: int, end: int) -> int: ...
    async def azremrangebyscore(self, key: str, min_score: float | str, max_score: float | str) -> int: ...
    async def azpopmin(self, key: str, count: int | None = None) -> list[tuple[bytes, float]]: ...
    async def azpopmax(self, key: str, count: int | None = None) -> list[tuple[bytes, float]]: ...
    async def azmscore(self, key: str, *members: bytes | int) -> list[float | None]: ...
    def xadd(
        self,
        key: str,
        fields: dict[str, bytes | int],
        entry_id: str = "*",
        maxlen: int | None = None,
        approximate: bool = True,
        nomkstream: bool = False,
        minid: str | None = None,
        limit: int | None = None,
    ) -> str: ...
    def xlen(self, key: str) -> int: ...
    def xrange(
        self,
        key: str,
        start: str = "-",
        end: str = "+",
        count: int | None = None,
    ) -> list[tuple[str, dict[str, bytes]]]: ...
    def xrevrange(
        self,
        key: str,
        end: str = "+",
        start: str = "-",
        count: int | None = None,
    ) -> list[tuple[str, dict[str, bytes]]]: ...
    def xread(
        self,
        streams: dict[str, str],
        count: int | None = None,
        block: int | None = None,
    ) -> dict[str, list[tuple[str, dict[str, bytes]]]] | None: ...
    def xtrim(
        self,
        key: str,
        maxlen: int | None = None,
        approximate: bool = True,
        minid: str | None = None,
        limit: int | None = None,
    ) -> int: ...
    def xdel(self, key: str, *entry_ids: str) -> int: ...
    def xinfo_stream(self, key: str, full: bool = False) -> dict[str, Any]: ...
    def xinfo_groups(self, key: str) -> list[dict[str, Any]]: ...
    def xinfo_consumers(self, key: str, group: str) -> list[dict[str, Any]]: ...
    def xgroup_create(
        self,
        key: str,
        group: str,
        entry_id: str = "$",
        mkstream: bool = False,
        entries_read: int | None = None,
    ) -> bool: ...
    def xgroup_destroy(self, key: str, group: str) -> int: ...
    def xgroup_setid(self, key: str, group: str, entry_id: str, entries_read: int | None = None) -> bool: ...
    def xgroup_delconsumer(self, key: str, group: str, consumer: str) -> int: ...
    def xreadgroup(
        self,
        group: str,
        consumer: str,
        streams: dict[str, str],
        count: int | None = None,
        block: int | None = None,
        noack: bool = False,
    ) -> dict[str, list[tuple[str, dict[str, bytes]]]] | None: ...
    def xack(self, key: str, group: str, *entry_ids: str) -> int: ...
    def xpending(
        self,
        key: str,
        group: str,
        start: str | None = None,
        end: str | None = None,
        count: int | None = None,
        consumer: str | None = None,
        idle: int | None = None,
    ) -> dict[str, Any] | list[dict[str, Any]]: ...
    def xclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        entry_ids: list[str],
        idle: int | None = None,
        time: int | None = None,
        retrycount: int | None = None,
        force: bool = False,
        justid: bool = False,
    ) -> list[tuple[str, dict[str, bytes]]] | list[str]: ...
    def xautoclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        start_id: str = "0-0",
        count: int | None = None,
        justid: bool = False,
    ) -> tuple[str, list[tuple[str, dict[str, bytes]]] | list[str], list[str]]: ...
    async def axadd(
        self,
        key: str,
        fields: dict[str, bytes | int],
        entry_id: str = "*",
        maxlen: int | None = None,
        approximate: bool = True,
        nomkstream: bool = False,
        minid: str | None = None,
        limit: int | None = None,
    ) -> str: ...
    async def axlen(self, key: str) -> int: ...
    async def axrange(
        self,
        key: str,
        start: str = "-",
        end: str = "+",
        count: int | None = None,
    ) -> list[tuple[str, dict[str, bytes]]]: ...
    async def axrevrange(
        self,
        key: str,
        end: str = "+",
        start: str = "-",
        count: int | None = None,
    ) -> list[tuple[str, dict[str, bytes]]]: ...
    async def axread(
        self,
        streams: dict[str, str],
        count: int | None = None,
        block: int | None = None,
    ) -> dict[str, list[tuple[str, dict[str, bytes]]]] | None: ...
    async def axtrim(
        self,
        key: str,
        maxlen: int | None = None,
        approximate: bool = True,
        minid: str | None = None,
        limit: int | None = None,
    ) -> int: ...
    async def axdel(self, key: str, *entry_ids: str) -> int: ...
    async def axinfo_stream(self, key: str, full: bool = False) -> dict[str, Any]: ...
    async def axinfo_groups(self, key: str) -> list[dict[str, Any]]: ...
    async def axinfo_consumers(self, key: str, group: str) -> list[dict[str, Any]]: ...
    async def axgroup_create(
        self,
        key: str,
        group: str,
        entry_id: str = "$",
        mkstream: bool = False,
        entries_read: int | None = None,
    ) -> bool: ...
    async def axgroup_destroy(self, key: str, group: str) -> int: ...
    async def axgroup_setid(self, key: str, group: str, entry_id: str, entries_read: int | None = None) -> bool: ...
    async def axgroup_delconsumer(self, key: str, group: str, consumer: str) -> int: ...
    async def axreadgroup(
        self,
        group: str,
        consumer: str,
        streams: dict[str, str],
        count: int | None = None,
        block: int | None = None,
        noack: bool = False,
    ) -> dict[str, list[tuple[str, dict[str, bytes]]]] | None: ...
    async def axack(self, key: str, group: str, *entry_ids: str) -> int: ...
    async def axpending(
        self,
        key: str,
        group: str,
        start: str | None = None,
        end: str | None = None,
        count: int | None = None,
        consumer: str | None = None,
        idle: int | None = None,
    ) -> dict[str, Any] | list[dict[str, Any]]: ...
    async def axclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        entry_ids: list[str],
        idle: int | None = None,
        time: int | None = None,
        retrycount: int | None = None,
        force: bool = False,
        justid: bool = False,
    ) -> list[tuple[str, dict[str, bytes]]] | list[str]: ...
    async def axautoclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        start_id: str = "0-0",
        count: int | None = None,
        justid: bool = False,
    ) -> tuple[str, list[tuple[str, dict[str, bytes]]] | list[str], list[str]]: ...
    def eval(self, script: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    async def aeval(self, script: str, numkeys: int, *keys_and_args: Any) -> Any: ...


__all__ = [
    "RespAdapterProtocol",
    "RespAsyncPipelineProtocol",
    "RespPipelineProtocol",
]
