"""Adapter-layer Protocols.

These ``typing.Protocol`` classes formalize the contracts the cache and
pipeline layers rely on.

- :class:`KeyValuePipelineProtocol` — pipeline-adapter contract.
- :class:`KeyValueAdapterProtocol` — adapter contract; what
  :class:`~django_cachex.cache.default.KeyValueCache` calls on its
  underlying adapter. Concrete adapters
  (:class:`~django_cachex.adapters.valkey_py.ValkeyPyAdapter`,
  :class:`~django_cachex.adapters.redis_rs.RedisRsValkeyAdapter`,
  :class:`~django_cachex.adapters.valkey_glide.ValkeyGlideAdapter`)
  inherit from this Protocol so the contract is explicit at the class
  declaration; the inherited method bodies (``...``) are shadowed by each
  driver's real implementations.

The cache-layer surface lives in
:mod:`django_cachex.cache.protocols` (:class:`~django_cachex.cache.protocols.CachexProtocol`).
"""

from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Iterable, Iterator, Mapping, Sequence

    from django_cachex.adapters.pipeline import BaseKeyValuePipelineAdapter
    from django_cachex.types import AbsExpiryT, ExpiryT, KeyT, KeyType, _Set


@runtime_checkable
class KeyValuePipelineProtocol(Protocol):
    """Pipeline-adapter contract: collect ops, batch-execute, return raw results.

    Concrete implementations are
    :class:`~django_cachex.adapters.pipeline.BaseKeyValuePipelineAdapter`
    subclasses (one per driver). They expose the cachex pipeline method
    surface — ``set``/``lpush``/``hset``/``zadd``/... — but those are not
    enumerated here; the ``Pipeline`` wrapper queues them dynamically and
    type-checkers verify them per-call.
    """

    def execute(self) -> list[Any]: ...
    def reset(self) -> None: ...


@runtime_checkable
class KeyValueAdapterProtocol(Protocol):
    """Wire-level adapter contract — every command + topology hook the cache calls.

    Concrete adapters inherit from this Protocol so the full ~200-method
    surface is declared in one place. Adapter implementations override
    every method; the ``...`` bodies inherited from this Protocol are
    therefore shadowed and never executed at runtime.
    """

    def __init__(self, servers: list[str], **options: Any) -> None: ...

    # Private-ish stampede helpers — called by ``KeyValueCache`` to resolve
    # per-call overrides against the adapter's instance config.
    def _resolve_stampede(self, stampede_prevention: bool | dict | None = None) -> Any: ...
    def _get_timeout_with_buffer(
        self,
        timeout: int | None,
        stampede_prevention: bool | dict | None = None,
    ) -> int | None: ...

    def get_client(self, key: KeyT | None = None, *, write: bool = False) -> Any: ...
    def get_async_client(self, key: KeyT | None = None, *, write: bool = False) -> Any: ...
    def add(
        self,
        key: KeyT,
        value: Any,
        timeout: int | None,
        *,
        stampede_prevention: bool | dict | None = None,
    ) -> bool: ...
    async def aadd(
        self,
        key: KeyT,
        value: Any,
        timeout: int | None,
        *,
        stampede_prevention: bool | dict | None = None,
    ) -> bool: ...
    def get(self, key: KeyT, *, stampede_prevention: bool | dict | None = None) -> Any: ...
    async def aget(self, key: KeyT, *, stampede_prevention: bool | dict | None = None) -> Any: ...
    def set(
        self,
        key: KeyT,
        value: Any,
        timeout: int | None,
        *,
        stampede_prevention: bool | dict | None = None,
    ) -> None: ...
    async def aset(
        self,
        key: KeyT,
        value: Any,
        timeout: int | None,
        *,
        stampede_prevention: bool | dict | None = None,
    ) -> None: ...
    def set_with_flags(
        self,
        key: KeyT,
        value: Any,
        timeout: int | None,
        *,
        nx: bool = False,
        xx: bool = False,
        get: bool = False,
        stampede_prevention: bool | dict | None = None,
    ) -> bool | Any: ...
    async def aset_with_flags(
        self,
        key: KeyT,
        value: Any,
        timeout: int | None,
        *,
        nx: bool = False,
        xx: bool = False,
        get: bool = False,
        stampede_prevention: bool | dict | None = None,
    ) -> bool | Any: ...
    def touch(self, key: KeyT, timeout: int | None) -> bool: ...
    async def atouch(self, key: KeyT, timeout: int | None) -> bool: ...
    def delete(self, key: KeyT) -> bool: ...
    async def adelete(self, key: KeyT) -> bool: ...
    def get_many(self, keys: Iterable[KeyT], *, stampede_prevention: bool | dict | None = None) -> dict[KeyT, Any]: ...
    async def aget_many(
        self,
        keys: Iterable[KeyT],
        *,
        stampede_prevention: bool | dict | None = None,
    ) -> dict[KeyT, Any]: ...
    def has_key(self, key: KeyT) -> bool: ...
    async def ahas_key(self, key: KeyT) -> bool: ...
    def type(self, key: KeyT) -> KeyType | None: ...
    async def atype(self, key: KeyT) -> KeyType | None: ...
    def incr(self, key: KeyT, delta: int = 1) -> int: ...
    async def aincr(self, key: KeyT, delta: int = 1) -> int: ...
    def set_many(
        self,
        data: Mapping[KeyT, Any],
        timeout: int | None,
        *,
        stampede_prevention: bool | dict | None = None,
    ) -> list: ...
    async def aset_many(
        self,
        data: Mapping[KeyT, Any],
        timeout: int | None,
        *,
        stampede_prevention: bool | dict | None = None,
    ) -> list: ...
    def delete_many(self, keys: Sequence[KeyT]) -> int: ...
    async def adelete_many(self, keys: Sequence[KeyT]) -> int: ...
    def clear(self) -> bool: ...
    async def aclear(self) -> bool: ...
    def close(self, **kwargs: Any) -> None: ...
    async def aclose(self, **kwargs: Any) -> None: ...
    def ttl(self, key: KeyT) -> int | None: ...
    def pttl(self, key: KeyT) -> int | None: ...
    def expiretime(self, key: KeyT) -> int | None: ...
    def expire(self, key: KeyT, timeout: ExpiryT) -> bool: ...
    def pexpire(self, key: KeyT, timeout: ExpiryT) -> bool: ...
    def expireat(self, key: KeyT, when: AbsExpiryT) -> bool: ...
    def pexpireat(self, key: KeyT, when: AbsExpiryT) -> bool: ...
    def persist(self, key: KeyT) -> bool: ...
    async def attl(self, key: KeyT) -> int | None: ...
    async def apttl(self, key: KeyT) -> int | None: ...
    async def aexpiretime(self, key: KeyT) -> int | None: ...
    async def aexpire(self, key: KeyT, timeout: ExpiryT) -> bool: ...
    async def apexpire(self, key: KeyT, timeout: ExpiryT) -> bool: ...
    async def aexpireat(self, key: KeyT, when: AbsExpiryT) -> bool: ...
    async def apexpireat(self, key: KeyT, when: AbsExpiryT) -> bool: ...
    async def apersist(self, key: KeyT) -> bool: ...
    def keys(self, pattern: str) -> list[str]: ...
    def iter_keys(self, pattern: str, itersize: int | None = None) -> Iterator[str]: ...
    def scan(
        self,
        cursor: int = 0,
        match: str | None = None,
        count: int | None = None,
        _type: str | None = None,
    ) -> tuple[int, list[str]]: ...
    async def ascan(
        self,
        cursor: int = 0,
        match: str | None = None,
        count: int | None = None,
        _type: str | None = None,
    ) -> tuple[int, list[str]]: ...
    def delete_pattern(self, pattern: str, itersize: int | None = None) -> int: ...
    def rename(self, src: KeyT, dst: KeyT) -> bool: ...
    def renamenx(self, src: KeyT, dst: KeyT) -> bool: ...
    async def akeys(self, pattern: str) -> list[str]: ...
    # Async generator: declared with plain ``def`` (not ``async def``) so async
    # generator overrides have a compatible signature — mypy types
    # ``async def -> AsyncIterator[X]`` as ``Coroutine[..., AsyncIterator[X]]``.
    def aiter_keys(self, pattern: str, itersize: int | None = None) -> AsyncIterator[str]: ...
    async def adelete_pattern(self, pattern: str, itersize: int | None = None) -> int: ...
    async def arename(self, src: KeyT, dst: KeyT) -> bool: ...
    async def arenamenx(self, src: KeyT, dst: KeyT) -> bool: ...
    def lock(
        self,
        key: str,
        timeout: float | None = None,
        sleep: float = 0.1,
        *,
        blocking: bool = True,
        blocking_timeout: float | None = None,
        thread_local: bool = True,
    ) -> Any: ...
    def alock(
        self,
        key: str,
        timeout: float | None = None,
        sleep: float = 0.1,
        *,
        blocking: bool = True,
        blocking_timeout: float | None = None,
        thread_local: bool = True,
    ) -> Any: ...
    def pipeline(self, *, transaction: bool = True) -> BaseKeyValuePipelineAdapter: ...
    def info(self, section: str | None = None) -> dict[str, Any]: ...
    def slowlog_get(self, count: int = 10) -> list[dict[str, Any]]: ...
    def slowlog_len(self) -> int: ...
    def hset(
        self,
        key: KeyT,
        field: str | None = None,
        value: Any = None,
        mapping: Mapping[str, Any] | None = None,
        items: list[Any] | None = None,
    ) -> int: ...
    def hsetnx(self, key: KeyT, field: str, value: Any) -> bool: ...
    def hget(self, key: KeyT, field: str) -> Any | None: ...
    def hmget(self, key: KeyT, *fields: str) -> list[Any | None]: ...
    def hgetall(self, key: KeyT) -> dict[str, Any]: ...
    def hdel(self, key: KeyT, *fields: str) -> int: ...
    def hexists(self, key: KeyT, field: str) -> bool: ...
    def hlen(self, key: KeyT) -> int: ...
    def hkeys(self, key: KeyT) -> list[str]: ...
    def hvals(self, key: KeyT) -> list[Any]: ...
    def hincrby(self, key: KeyT, field: str, amount: int = 1) -> int: ...
    def hincrbyfloat(self, key: KeyT, field: str, amount: float = 1.0) -> float: ...
    async def ahset(
        self,
        key: KeyT,
        field: str | None = None,
        value: Any = None,
        mapping: Mapping[str, Any] | None = None,
        items: list[Any] | None = None,
    ) -> int: ...
    async def ahsetnx(self, key: KeyT, field: str, value: Any) -> bool: ...
    async def ahget(self, key: KeyT, field: str) -> Any | None: ...
    async def ahmget(self, key: KeyT, *fields: str) -> list[Any | None]: ...
    async def ahgetall(self, key: KeyT) -> dict[str, Any]: ...
    async def ahdel(self, key: KeyT, *fields: str) -> int: ...
    async def ahexists(self, key: KeyT, field: str) -> bool: ...
    async def ahlen(self, key: KeyT) -> int: ...
    async def ahkeys(self, key: KeyT) -> list[str]: ...
    async def ahvals(self, key: KeyT) -> list[Any]: ...
    async def ahincrby(self, key: KeyT, field: str, amount: int = 1) -> int: ...
    async def ahincrbyfloat(self, key: KeyT, field: str, amount: float = 1.0) -> float: ...
    def lpush(self, key: KeyT, *values: Any) -> int: ...
    def rpush(self, key: KeyT, *values: Any) -> int: ...
    def lpop(self, key: KeyT, count: int | None = None) -> Any | list[Any] | None: ...
    def rpop(self, key: KeyT, count: int | None = None) -> Any | list[Any] | None: ...
    def llen(self, key: KeyT) -> int: ...
    def lpos(
        self,
        key: KeyT,
        value: Any,
        rank: int | None = None,
        count: int | None = None,
        maxlen: int | None = None,
    ) -> int | list[int] | None: ...
    def lmove(self, src: KeyT, dst: KeyT, wherefrom: str, whereto: str) -> Any | None: ...
    def lrange(self, key: KeyT, start: int, end: int) -> list[Any]: ...
    def lindex(self, key: KeyT, index: int) -> Any | None: ...
    def lset(self, key: KeyT, index: int, value: Any) -> bool: ...
    def lrem(self, key: KeyT, count: int, value: Any) -> int: ...
    def ltrim(self, key: KeyT, start: int, end: int) -> bool: ...
    def linsert(self, key: KeyT, where: str, pivot: Any, value: Any) -> int: ...
    def blpop(self, keys: KeyT | Sequence[KeyT], timeout: float = 0) -> tuple[str, Any] | None: ...
    def brpop(self, keys: KeyT | Sequence[KeyT], timeout: float = 0) -> tuple[str, Any] | None: ...
    def blmove(
        self,
        src: KeyT,
        dst: KeyT,
        timeout: float,
        wherefrom: str = "LEFT",
        whereto: str = "RIGHT",
    ) -> Any | None: ...
    async def alpush(self, key: KeyT, *values: Any) -> int: ...
    async def arpush(self, key: KeyT, *values: Any) -> int: ...
    async def alpop(self, key: KeyT, count: int | None = None) -> Any | list[Any] | None: ...
    async def arpop(self, key: KeyT, count: int | None = None) -> Any | list[Any] | None: ...
    async def allen(self, key: KeyT) -> int: ...
    async def alpos(
        self,
        key: KeyT,
        value: Any,
        rank: int | None = None,
        count: int | None = None,
        maxlen: int | None = None,
    ) -> int | list[int] | None: ...
    async def almove(self, src: KeyT, dst: KeyT, wherefrom: str, whereto: str) -> Any | None: ...
    async def alrange(self, key: KeyT, start: int, end: int) -> list[Any]: ...
    async def alindex(self, key: KeyT, index: int) -> Any | None: ...
    async def alset(self, key: KeyT, index: int, value: Any) -> bool: ...
    async def alrem(self, key: KeyT, count: int, value: Any) -> int: ...
    async def altrim(self, key: KeyT, start: int, end: int) -> bool: ...
    async def alinsert(self, key: KeyT, where: str, pivot: Any, value: Any) -> int: ...
    async def ablpop(self, keys: KeyT | Sequence[KeyT], timeout: float = 0) -> tuple[str, Any] | None: ...
    async def abrpop(self, keys: KeyT | Sequence[KeyT], timeout: float = 0) -> tuple[str, Any] | None: ...
    async def ablmove(
        self,
        src: KeyT,
        dst: KeyT,
        timeout: float,
        wherefrom: str = "LEFT",
        whereto: str = "RIGHT",
    ) -> Any | None: ...
    def sadd(self, key: KeyT, *members: Any) -> int: ...
    def srem(self, key: KeyT, *members: Any) -> int: ...
    def smembers(self, key: KeyT) -> _Set[Any]: ...
    def sismember(self, key: KeyT, member: Any) -> bool: ...
    def scard(self, key: KeyT) -> int: ...
    def spop(self, key: KeyT, count: int | None = None) -> Any | list[Any] | None: ...
    def srandmember(self, key: KeyT, count: int | None = None) -> Any | list[Any] | None: ...
    def smove(self, src: KeyT, dst: KeyT, member: Any) -> bool: ...
    def sdiff(self, keys: KeyT | Sequence[KeyT]) -> _Set[Any]: ...
    def sdiffstore(self, dest: KeyT, keys: KeyT | Sequence[KeyT]) -> int: ...
    def sinter(self, keys: KeyT | Sequence[KeyT]) -> _Set[Any]: ...
    def sinterstore(self, dest: KeyT, keys: KeyT | Sequence[KeyT]) -> int: ...
    def sunion(self, keys: KeyT | Sequence[KeyT]) -> _Set[Any]: ...
    def sunionstore(self, dest: KeyT, keys: KeyT | Sequence[KeyT]) -> int: ...
    def smismember(self, key: KeyT, *members: Any) -> list[bool]: ...
    def sscan(
        self,
        key: KeyT,
        cursor: int = 0,
        match: str | None = None,
        count: int | None = None,
    ) -> tuple[int, _Set[Any]]: ...
    def sscan_iter(self, key: KeyT, match: str | None = None, count: int | None = None) -> Iterator[Any]: ...
    async def asadd(self, key: KeyT, *members: Any) -> int: ...
    async def asrem(self, key: KeyT, *members: Any) -> int: ...
    async def asmembers(self, key: KeyT) -> _Set[Any]: ...
    async def asismember(self, key: KeyT, member: Any) -> bool: ...
    async def ascard(self, key: KeyT) -> int: ...
    async def aspop(self, key: KeyT, count: int | None = None) -> Any | list[Any] | None: ...
    async def asrandmember(self, key: KeyT, count: int | None = None) -> Any | list[Any] | None: ...
    async def asmove(self, src: KeyT, dst: KeyT, member: Any) -> bool: ...
    async def asdiff(self, keys: KeyT | Sequence[KeyT]) -> _Set[Any]: ...
    async def asdiffstore(self, dest: KeyT, keys: KeyT | Sequence[KeyT]) -> int: ...
    async def asinter(self, keys: KeyT | Sequence[KeyT]) -> _Set[Any]: ...
    async def asinterstore(self, dest: KeyT, keys: KeyT | Sequence[KeyT]) -> int: ...
    async def asunion(self, keys: KeyT | Sequence[KeyT]) -> _Set[Any]: ...
    async def asunionstore(self, dest: KeyT, keys: KeyT | Sequence[KeyT]) -> int: ...
    async def asmismember(self, key: KeyT, *members: Any) -> list[bool]: ...
    async def asscan(
        self,
        key: KeyT,
        cursor: int = 0,
        match: str | None = None,
        count: int | None = None,
    ) -> tuple[int, _Set[Any]]: ...
    def asscan_iter(  # async generator: see note on ``aiter_keys`` for ``def`` (not ``async def``)
        self,
        key: KeyT,
        match: str | None = None,
        count: int | None = None,
    ) -> AsyncIterator[Any]: ...
    def zadd(
        self,
        key: KeyT,
        mapping: Mapping[Any, float],
        *,
        nx: bool = False,
        xx: bool = False,
        gt: bool = False,
        lt: bool = False,
        ch: bool = False,
    ) -> int: ...
    def zrem(self, key: KeyT, *members: Any) -> int: ...
    def zscore(self, key: KeyT, member: Any) -> float | None: ...
    def zrank(self, key: KeyT, member: Any) -> int | None: ...
    def zrevrank(self, key: KeyT, member: Any) -> int | None: ...
    def zcard(self, key: KeyT) -> int: ...
    def zcount(self, key: KeyT, min_score: float | str, max_score: float | str) -> int: ...
    def zincrby(self, key: KeyT, amount: float, member: Any) -> float: ...
    def zrange(
        self,
        key: KeyT,
        start: int,
        end: int,
        *,
        withscores: bool = False,
    ) -> list[Any] | list[tuple[Any, float]]: ...
    def zrevrange(
        self,
        key: KeyT,
        start: int,
        end: int,
        *,
        withscores: bool = False,
    ) -> list[Any] | list[tuple[Any, float]]: ...
    def zrangebyscore(
        self,
        key: KeyT,
        min_score: float | str,
        max_score: float | str,
        *,
        start: int | None = None,
        num: int | None = None,
        withscores: bool = False,
    ) -> list[Any] | list[tuple[Any, float]]: ...
    def zrevrangebyscore(
        self,
        key: KeyT,
        max_score: float | str,
        min_score: float | str,
        *,
        start: int | None = None,
        num: int | None = None,
        withscores: bool = False,
    ) -> list[Any] | list[tuple[Any, float]]: ...
    def zremrangebyrank(self, key: KeyT, start: int, end: int) -> int: ...
    def zremrangebyscore(self, key: KeyT, min_score: float | str, max_score: float | str) -> int: ...
    def zpopmin(self, key: KeyT, count: int | None = None) -> list[tuple[Any, float]]: ...
    def zpopmax(self, key: KeyT, count: int | None = None) -> list[tuple[Any, float]]: ...
    def zmscore(self, key: KeyT, *members: Any) -> list[float | None]: ...
    async def azadd(
        self,
        key: KeyT,
        mapping: Mapping[Any, float],
        *,
        nx: bool = False,
        xx: bool = False,
        gt: bool = False,
        lt: bool = False,
        ch: bool = False,
    ) -> int: ...
    async def azrem(self, key: KeyT, *members: Any) -> int: ...
    async def azscore(self, key: KeyT, member: Any) -> float | None: ...
    async def azrank(self, key: KeyT, member: Any) -> int | None: ...
    async def azrevrank(self, key: KeyT, member: Any) -> int | None: ...
    async def azcard(self, key: KeyT) -> int: ...
    async def azcount(self, key: KeyT, min_score: float | str, max_score: float | str) -> int: ...
    async def azincrby(self, key: KeyT, amount: float, member: Any) -> float: ...
    async def azrange(
        self,
        key: KeyT,
        start: int,
        end: int,
        *,
        withscores: bool = False,
    ) -> list[Any] | list[tuple[Any, float]]: ...
    async def azrevrange(
        self,
        key: KeyT,
        start: int,
        end: int,
        *,
        withscores: bool = False,
    ) -> list[Any] | list[tuple[Any, float]]: ...
    async def azrangebyscore(
        self,
        key: KeyT,
        min_score: float | str,
        max_score: float | str,
        *,
        start: int | None = None,
        num: int | None = None,
        withscores: bool = False,
    ) -> list[Any] | list[tuple[Any, float]]: ...
    async def azrevrangebyscore(
        self,
        key: KeyT,
        max_score: float | str,
        min_score: float | str,
        *,
        start: int | None = None,
        num: int | None = None,
        withscores: bool = False,
    ) -> list[Any] | list[tuple[Any, float]]: ...
    async def azremrangebyrank(self, key: KeyT, start: int, end: int) -> int: ...
    async def azremrangebyscore(self, key: KeyT, min_score: float | str, max_score: float | str) -> int: ...
    async def azpopmin(self, key: KeyT, count: int | None = None) -> list[tuple[Any, float]]: ...
    async def azpopmax(self, key: KeyT, count: int | None = None) -> list[tuple[Any, float]]: ...
    async def azmscore(self, key: KeyT, *members: Any) -> list[float | None]: ...
    def xadd(
        self,
        key: KeyT,
        fields: dict[str, Any],
        entry_id: str = "*",
        maxlen: int | None = None,
        approximate: bool = True,
        nomkstream: bool = False,
        minid: str | None = None,
        limit: int | None = None,
    ) -> str: ...
    def _decode_stream_entries(self, results: list[tuple[Any, dict[Any, Any]]]) -> list[tuple[str, dict[str, Any]]]: ...
    def _decode_stream_results(
        self,
        results: list[tuple[Any, list[tuple[Any, dict[Any, Any]]]]],
    ) -> dict[str, list[tuple[str, dict[str, Any]]]]: ...
    def xlen(self, key: KeyT) -> int: ...
    def xrange(
        self,
        key: KeyT,
        start: str = "-",
        end: str = "+",
        count: int | None = None,
    ) -> list[tuple[str, dict[str, Any]]]: ...
    def xrevrange(
        self,
        key: KeyT,
        end: str = "+",
        start: str = "-",
        count: int | None = None,
    ) -> list[tuple[str, dict[str, Any]]]: ...
    def xread(
        self,
        streams: dict[KeyT, str],
        count: int | None = None,
        block: int | None = None,
    ) -> dict[str, list[tuple[str, dict[str, Any]]]] | None: ...
    def xtrim(
        self,
        key: KeyT,
        maxlen: int | None = None,
        approximate: bool = True,
        minid: str | None = None,
        limit: int | None = None,
    ) -> int: ...
    def xdel(self, key: KeyT, *entry_ids: str) -> int: ...
    def xinfo_stream(self, key: KeyT, full: bool = False) -> dict[str, Any]: ...
    def xinfo_groups(self, key: KeyT) -> list[dict[str, Any]]: ...
    def xinfo_consumers(self, key: KeyT, group: str) -> list[dict[str, Any]]: ...
    def xgroup_create(
        self,
        key: KeyT,
        group: str,
        entry_id: str = "$",
        mkstream: bool = False,
        entries_read: int | None = None,
    ) -> bool: ...
    def xgroup_destroy(self, key: KeyT, group: str) -> int: ...
    def xgroup_setid(self, key: KeyT, group: str, entry_id: str, entries_read: int | None = None) -> bool: ...
    def xgroup_delconsumer(self, key: KeyT, group: str, consumer: str) -> int: ...
    def xreadgroup(
        self,
        group: str,
        consumer: str,
        streams: dict[KeyT, str],
        count: int | None = None,
        block: int | None = None,
        noack: bool = False,
    ) -> dict[str, list[tuple[str, dict[str, Any]]]] | None: ...
    def xack(self, key: KeyT, group: str, *entry_ids: str) -> int: ...
    def xpending(
        self,
        key: KeyT,
        group: str,
        start: str | None = None,
        end: str | None = None,
        count: int | None = None,
        consumer: str | None = None,
        idle: int | None = None,
    ) -> dict[str, Any] | list[dict[str, Any]]: ...
    def xclaim(
        self,
        key: KeyT,
        group: str,
        consumer: str,
        min_idle_time: int,
        entry_ids: list[str],
        idle: int | None = None,
        time: int | None = None,
        retrycount: int | None = None,
        force: bool = False,
        justid: bool = False,
    ) -> list[tuple[str, dict[str, Any]]] | list[str]: ...
    def xautoclaim(
        self,
        key: KeyT,
        group: str,
        consumer: str,
        min_idle_time: int,
        start_id: str = "0-0",
        count: int | None = None,
        justid: bool = False,
    ) -> tuple[str, list[tuple[str, dict[str, Any]]] | list[str], list[str]]: ...
    async def axadd(
        self,
        key: KeyT,
        fields: dict[str, Any],
        entry_id: str = "*",
        maxlen: int | None = None,
        approximate: bool = True,
        nomkstream: bool = False,
        minid: str | None = None,
        limit: int | None = None,
    ) -> str: ...
    async def axlen(self, key: KeyT) -> int: ...
    async def axrange(
        self,
        key: KeyT,
        start: str = "-",
        end: str = "+",
        count: int | None = None,
    ) -> list[tuple[str, dict[str, Any]]]: ...
    async def axrevrange(
        self,
        key: KeyT,
        end: str = "+",
        start: str = "-",
        count: int | None = None,
    ) -> list[tuple[str, dict[str, Any]]]: ...
    async def axread(
        self,
        streams: dict[KeyT, str],
        count: int | None = None,
        block: int | None = None,
    ) -> dict[str, list[tuple[str, dict[str, Any]]]] | None: ...
    async def axtrim(
        self,
        key: KeyT,
        maxlen: int | None = None,
        approximate: bool = True,
        minid: str | None = None,
        limit: int | None = None,
    ) -> int: ...
    async def axdel(self, key: KeyT, *entry_ids: str) -> int: ...
    async def axinfo_stream(self, key: KeyT, full: bool = False) -> dict[str, Any]: ...
    async def axinfo_groups(self, key: KeyT) -> list[dict[str, Any]]: ...
    async def axinfo_consumers(self, key: KeyT, group: str) -> list[dict[str, Any]]: ...
    async def axgroup_create(
        self,
        key: KeyT,
        group: str,
        entry_id: str = "$",
        mkstream: bool = False,
        entries_read: int | None = None,
    ) -> bool: ...
    async def axgroup_destroy(self, key: KeyT, group: str) -> int: ...
    async def axgroup_setid(self, key: KeyT, group: str, entry_id: str, entries_read: int | None = None) -> bool: ...
    async def axgroup_delconsumer(self, key: KeyT, group: str, consumer: str) -> int: ...
    async def axreadgroup(
        self,
        group: str,
        consumer: str,
        streams: dict[KeyT, str],
        count: int | None = None,
        block: int | None = None,
        noack: bool = False,
    ) -> dict[str, list[tuple[str, dict[str, Any]]]] | None: ...
    async def axack(self, key: KeyT, group: str, *entry_ids: str) -> int: ...
    async def axpending(
        self,
        key: KeyT,
        group: str,
        start: str | None = None,
        end: str | None = None,
        count: int | None = None,
        consumer: str | None = None,
        idle: int | None = None,
    ) -> dict[str, Any] | list[dict[str, Any]]: ...
    async def axclaim(
        self,
        key: KeyT,
        group: str,
        consumer: str,
        min_idle_time: int,
        entry_ids: list[str],
        idle: int | None = None,
        time: int | None = None,
        retrycount: int | None = None,
        force: bool = False,
        justid: bool = False,
    ) -> list[tuple[str, dict[str, Any]]] | list[str]: ...
    async def axautoclaim(
        self,
        key: KeyT,
        group: str,
        consumer: str,
        min_idle_time: int,
        start_id: str = "0-0",
        count: int | None = None,
        justid: bool = False,
    ) -> tuple[str, list[tuple[str, dict[str, Any]]] | list[str], list[str]]: ...
    def eval(self, script: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    async def aeval(self, script: str, numkeys: int, *keys_and_args: Any) -> Any: ...


__all__ = [
    "KeyValueAdapterProtocol",
    "KeyValuePipelineProtocol",
]
