# Generated stub for the maturin-built _driver Rust extension.
# Source: src/client.rs and src/async_bridge.rs. Regenerate via
# scripts/gen_driver_stub.py if you modify the pyo3 surface.

from collections.abc import Awaitable
from typing import Any

class RedisRsAwaitable:
    def __await__(self) -> Any: ...
    def cancel(self) -> bool: ...

class RedisRsDriver:
    @classmethod
    def connect_standard(
        cls,
        url: str,
        cache_max_size: int | None = None,
        cache_ttl_secs: int | None = None,
        ssl_ca_certs: str | None = None,
        ssl_certfile: str | None = None,
        ssl_keyfile: str | None = None,
    ) -> RedisRsDriver: ...
    @classmethod
    def connect_cluster(
        cls,
        urls: list[str],
        ssl_ca_certs: str | None = None,
        ssl_certfile: str | None = None,
        ssl_keyfile: str | None = None,
    ) -> RedisRsDriver: ...
    @classmethod
    def connect_sentinel(
        cls,
        sentinel_urls: list[str],
        service_name: str,
        db: int,
        cache_max_size: int | None = None,
        cache_ttl_secs: int | None = None,
        ssl_ca_certs: str | None = None,
        ssl_certfile: str | None = None,
        ssl_keyfile: str | None = None,
    ) -> RedisRsDriver: ...
    def cache_statistics(self) -> tuple[int, int, int] | None: ...
    def aget(self, key: str) -> Awaitable[Any]: ...
    def get(self, key: str) -> Any: ...
    def aset(self, key: str, value: bytes, ttl: int | None = None) -> Awaitable[Any]: ...
    def set(self, key: str, value: bytes, ttl: int | None = None) -> None: ...
    def aset_nx(self, key: str, value: bytes, ttl: int | None = None) -> Awaitable[Any]: ...
    def set_nx(self, key: str, value: bytes, ttl: int | None = None) -> bool: ...
    def adelete(self, key: str) -> Awaitable[Any]: ...
    def delete(self, key: str) -> int: ...
    def adelete_many(self, keys: list[str]) -> Awaitable[Any]: ...
    def delete_many(self, keys: list[str]) -> int: ...
    def amget(self, keys: list[str]) -> Awaitable[Any]: ...
    def mget(self, keys: list[str]) -> Any: ...
    def apipeline_set(self, entries: list[tuple[str, bytes]], ttl: int | None = None) -> Awaitable[Any]: ...
    def pipeline_set(self, entries: list[tuple[str, bytes]], ttl: int | None = None) -> None: ...
    def aincr_by(self, key: str, delta: int) -> Awaitable[Any]: ...
    def incr_by(self, key: str, delta: int) -> int: ...
    def aexists(self, key: str) -> Awaitable[Any]: ...
    def exists(self, key: str) -> bool: ...
    def aexpire(self, key: str, seconds: int) -> Awaitable[Any]: ...
    def expire(self, key: str, seconds: int) -> bool: ...
    def apersist(self, key: str) -> Awaitable[Any]: ...
    def persist(self, key: str) -> bool: ...
    def attl(self, key: str) -> Awaitable[Any]: ...
    def ttl(self, key: str) -> int: ...
    def apttl(self, key: str) -> Awaitable[Any]: ...
    def pttl(self, key: str) -> int: ...
    def aflushdb(self) -> Awaitable[Any]: ...
    def flushdb(self) -> None: ...
    def akeys(self, pattern: str) -> Awaitable[Any]: ...
    def keys(self, pattern: str) -> Any: ...
    def atype(self, key: str) -> Awaitable[Any]: ...
    def type(self, key: str) -> str: ...
    def ascan(self, pattern: str, count: int) -> Awaitable[Any]: ...
    def scan(self, pattern: str, count: int) -> Any: ...
    def adbsize(self) -> Awaitable[Any]: ...
    def dbsize(self) -> int: ...
    def ainfo(self) -> Awaitable[Any]: ...
    def info(self) -> Any: ...
    def aclient_list(self) -> Awaitable[Any]: ...
    def client_list(self) -> Any: ...
    def aconfig_get(self, parameter: str) -> Awaitable[Any]: ...
    def config_get(self, parameter: str) -> Any: ...
    def aobject_encoding(self, key: str) -> Awaitable[Any]: ...
    def object_encoding(self, key: str) -> str | None: ...
    def aobject_idletime(self, key: str) -> Awaitable[Any]: ...
    def object_idletime(self, key: str) -> int | None: ...
    def amemory_usage(self, key: str) -> Awaitable[Any]: ...
    def memory_usage(self, key: str) -> int | None: ...
    def alock_acquire(self, key: str, token: str, timeout_ms: int | None = None) -> Awaitable[Any]: ...
    def lock_acquire(self, key: str, token: str, timeout_ms: int | None = None) -> bool: ...
    def alock_release(self, key: str, token: str) -> Awaitable[Any]: ...
    def lock_release(self, key: str, token: str) -> int: ...
    def alock_extend(self, key: str, token: str, additional_ms: int) -> Awaitable[Any]: ...
    def lock_extend(self, key: str, token: str, additional_ms: int) -> int: ...
    def aeval(self, script: str, keys: list[str], args: list[bytes]) -> Awaitable[Any]: ...
    def eval(self, script: str, keys: list[str], args: list[bytes]) -> Any: ...
    def aevalsha(self, sha: str, keys: list[str], args: list[bytes]) -> Awaitable[Any]: ...
    def evalsha(self, sha: str, keys: list[str], args: list[bytes]) -> Any: ...
    def ascript_load(self, script: str) -> Awaitable[Any]: ...
    def script_load(self, script: str) -> str: ...
    def ascript_exists(self, sha: str) -> Awaitable[Any]: ...
    def script_exists(self, sha: str) -> bool: ...
    def apipeline_exec(self, commands: list[tuple[str, list[bytes]]], transaction: bool = False) -> Awaitable[Any]: ...
    def pipeline_exec(self, commands: list[tuple[str, list[bytes]]], transaction: bool = False) -> Any: ...
    def alpush(self, key: str, values: list[bytes]) -> Awaitable[Any]: ...
    def lpush(self, key: str, values: list[bytes]) -> int: ...
    def arpush(self, key: str, values: list[bytes]) -> Awaitable[Any]: ...
    def rpush(self, key: str, values: list[bytes]) -> int: ...
    def alpop(self, key: str) -> Awaitable[Any]: ...
    def lpop(self, key: str) -> Any: ...
    def arpop(self, key: str) -> Awaitable[Any]: ...
    def rpop(self, key: str) -> Any: ...
    def alrange(self, key: str, start: int, stop: int) -> Awaitable[Any]: ...
    def lrange(self, key: str, start: int, stop: int) -> Any: ...
    def allen(self, key: str) -> Awaitable[Any]: ...
    def llen(self, key: str) -> int: ...
    def alrem(self, key: str, count: int, value: bytes) -> Awaitable[Any]: ...
    def lrem(self, key: str, count: int, value: bytes) -> int: ...
    def alindex(self, key: str, index: int) -> Awaitable[Any]: ...
    def lindex(self, key: str, index: int) -> Any: ...
    def alset(self, key: str, index: int, value: bytes) -> Awaitable[Any]: ...
    def lset(self, key: str, index: int, value: bytes) -> None: ...
    def alinsert(self, key: str, before: bool, pivot: bytes, value: bytes) -> Awaitable[Any]: ...
    def linsert(self, key: str, before: bool, pivot: bytes, value: bytes) -> int: ...
    def altrim(self, key: str, start: int, stop: int) -> Awaitable[Any]: ...
    def ltrim(self, key: str, start: int, stop: int) -> None: ...
    def ablmove(
        self, source: str, destination: str, wherefrom: str, whereto: str, timeout: float
    ) -> Awaitable[Any]: ...
    def blmove(self, source: str, destination: str, wherefrom: str, whereto: str, timeout: float) -> Any: ...
    def ablmpop(self, timeout: float, keys: list[str], direction: str, count: int) -> Awaitable[Any]: ...
    def blmpop(self, timeout: float, keys: list[str], direction: str, count: int) -> Any: ...
    def ablpop(self, keys: list[str], timeout: float) -> Awaitable[tuple[str, bytes] | None]: ...
    def blpop(self, keys: list[str], timeout: float) -> tuple[str, bytes] | None: ...
    def abrpop(self, keys: list[str], timeout: float) -> Awaitable[tuple[str, bytes] | None]: ...
    def brpop(self, keys: list[str], timeout: float) -> tuple[str, bytes] | None: ...
    def ascan_one(self, cursor: int, pattern: str, count: int) -> Awaitable[tuple[int, list[str]]]: ...
    def scan_one(self, cursor: int, pattern: str, count: int) -> tuple[int, list[str]]: ...
    def ahget(self, key: str, field: str) -> Awaitable[Any]: ...
    def hget(self, key: str, field: str) -> Any: ...
    def ahset(self, key: str, field: str, value: bytes) -> Awaitable[Any]: ...
    def hset(self, key: str, field: str, value: bytes) -> int: ...
    def ahgetall(self, key: str) -> Awaitable[Any]: ...
    def hgetall(self, key: str) -> Any: ...
    def ahdel(self, key: str, fields: list[str]) -> Awaitable[Any]: ...
    def hdel(self, key: str, fields: list[str]) -> int: ...
    def ahincrby(self, key: str, field: str, delta: int) -> Awaitable[Any]: ...
    def hincrby(self, key: str, field: str, delta: int) -> int: ...
    def ahkeys(self, key: str) -> Awaitable[Any]: ...
    def hkeys(self, key: str) -> Any: ...
    def ahvals(self, key: str) -> Awaitable[Any]: ...
    def hvals(self, key: str) -> Any: ...
    def ahexists(self, key: str, field: str) -> Awaitable[Any]: ...
    def hexists(self, key: str, field: str) -> bool: ...
    def ahlen(self, key: str) -> Awaitable[Any]: ...
    def hlen(self, key: str) -> int: ...
    def ahmget(self, key: str, fields: list[str]) -> Awaitable[Any]: ...
    def hmget(self, key: str, fields: list[str]) -> Any: ...
    def ahmset(self, key: str, fields: list[tuple[str, bytes]]) -> Awaitable[Any]: ...
    def hmset(self, key: str, fields: list[tuple[str, bytes]]) -> None: ...
    def asadd(self, key: str, members: list[bytes]) -> Awaitable[Any]: ...
    def sadd(self, key: str, members: list[bytes]) -> int: ...
    def asrem(self, key: str, members: list[bytes]) -> Awaitable[Any]: ...
    def srem(self, key: str, members: list[bytes]) -> int: ...
    def asmembers(self, key: str) -> Awaitable[Any]: ...
    def smembers(self, key: str) -> Any: ...
    def asismember(self, key: str, member: bytes) -> Awaitable[Any]: ...
    def sismember(self, key: str, member: bytes) -> bool: ...
    def ascard(self, key: str) -> Awaitable[Any]: ...
    def scard(self, key: str) -> int: ...
    def asinter(self, keys: list[str]) -> Awaitable[Any]: ...
    def sinter(self, keys: list[str]) -> Any: ...
    def asunion(self, keys: list[str]) -> Awaitable[Any]: ...
    def sunion(self, keys: list[str]) -> Any: ...
    def asdiff(self, keys: list[str]) -> Awaitable[Any]: ...
    def sdiff(self, keys: list[str]) -> Any: ...
    def azadd(self, key: str, members: list[tuple[bytes, float]]) -> Awaitable[Any]: ...
    def zadd(self, key: str, members: list[tuple[bytes, float]]) -> int: ...
    def azrem(self, key: str, members: list[bytes]) -> Awaitable[Any]: ...
    def zrem(self, key: str, members: list[bytes]) -> int: ...
    def azrange(self, key: str, start: int, stop: int, with_scores: bool = False) -> Awaitable[Any]: ...
    def zrange(self, key: str, start: int, stop: int, with_scores: bool = False) -> Any: ...
    def azrangebyscore(self, key: str, min: str, max: str, with_scores: bool = False) -> Awaitable[Any]: ...
    def zrangebyscore(self, key: str, min: str, max: str, with_scores: bool = False) -> Any: ...
    def azrevrange(self, key: str, start: int, stop: int, with_scores: bool = False) -> Awaitable[Any]: ...
    def zrevrange(self, key: str, start: int, stop: int, with_scores: bool = False) -> Any: ...
    def azincrby(self, key: str, member: bytes, delta: float) -> Awaitable[Any]: ...
    def zincrby(self, key: str, member: bytes, delta: float) -> float: ...
    def azcard(self, key: str) -> Awaitable[Any]: ...
    def zcard(self, key: str) -> int: ...
    def azscore(self, key: str, member: bytes) -> Awaitable[Any]: ...
    def zscore(self, key: str, member: bytes) -> float | None: ...
    def azrank(self, key: str, member: bytes) -> Awaitable[Any]: ...
    def zrank(self, key: str, member: bytes) -> int | None: ...
    def azcount(self, key: str, min: str, max: str) -> Awaitable[Any]: ...
    def zcount(self, key: str, min: str, max: str) -> int: ...
    def azpopmin(self, key: str, count: int = 1) -> Awaitable[Any]: ...
    def zpopmin(self, key: str, count: int = 1) -> Any: ...
    def azpopmax(self, key: str, count: int = 1) -> Awaitable[Any]: ...
    def zpopmax(self, key: str, count: int = 1) -> Any: ...
    def axadd(self, key: str, id: str, fields: list[tuple[str, bytes]]) -> Awaitable[Any]: ...
    def xadd(self, key: str, id: str, fields: list[tuple[str, bytes]]) -> str: ...
    def axlen(self, key: str) -> Awaitable[Any]: ...
    def xlen(self, key: str) -> int: ...
    def axrange(self, key: str, start: str, end: str, count: int | None = None) -> Awaitable[Any]: ...
    def xrange(self, key: str, start: str, end: str, count: int | None = None) -> Any: ...
    def axread(self, keys: list[str], ids: list[str], count: int | None = None) -> Awaitable[Any]: ...
    def xread(self, keys: list[str], ids: list[str], count: int | None = None) -> Any: ...
    def axreadgroup(
        self, group: str, consumer: str, keys: list[str], ids: list[str], count: int | None = None
    ) -> Awaitable[Any]: ...
    def xreadgroup(
        self, group: str, consumer: str, keys: list[str], ids: list[str], count: int | None = None
    ) -> Any: ...
    def axack(self, key: str, group: str, ids: list[str]) -> Awaitable[Any]: ...
    def xack(self, key: str, group: str, ids: list[str]) -> int: ...
    def axtrim(self, key: str, max_len: int, approximate: bool = False) -> Awaitable[Any]: ...
    def xtrim(self, key: str, max_len: int, approximate: bool = False) -> int: ...
    def axgroup_create(self, key: str, group: str, id: str, mkstream: bool = False) -> Awaitable[Any]: ...
    def xgroup_create(self, key: str, group: str, id: str, mkstream: bool = False) -> None: ...
    def axpending(self, key: str, group: str) -> Awaitable[Any]: ...
    def xpending(self, key: str, group: str) -> Any: ...
    def axpending_range(
        self,
        key: str,
        group: str,
        start: str,
        end: str,
        count: int,
        consumer: str | None = None,
        idle: int | None = None,
    ) -> Awaitable[Any]: ...
    def xpending_range(
        self,
        key: str,
        group: str,
        start: str,
        end: str,
        count: int,
        consumer: str | None = None,
        idle: int | None = None,
    ) -> Any: ...
    def axclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        ids: list[str],
        idle: int | None = None,
        time_ms: int | None = None,
        retrycount: int | None = None,
        force: bool = False,
        justid: bool = False,
    ) -> Awaitable[Any]: ...
    def xclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        ids: list[str],
        idle: int | None = None,
        time_ms: int | None = None,
        retrycount: int | None = None,
        force: bool = False,
        justid: bool = False,
    ) -> Any: ...
    def axautoclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        start: str,
        count: int | None = None,
        justid: bool = False,
    ) -> Awaitable[Any]: ...
    def xautoclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        start: str,
        count: int | None = None,
        justid: bool = False,
    ) -> Any: ...

def _test_resolved_bytes(value: bytes) -> RedisRsAwaitable: ...
def _test_resolved_none() -> RedisRsAwaitable: ...
def _test_resolved_int(value: int) -> RedisRsAwaitable: ...
def _test_delayed_bytes(value: bytes, delay_ms: int) -> RedisRsAwaitable: ...
def _test_pending() -> RedisRsAwaitable: ...
def _test_dropped() -> RedisRsAwaitable: ...
def _test_error(message: str) -> RedisRsAwaitable: ...
def _test_server_error(message: str) -> RedisRsAwaitable: ...
