# Generated stub for the maturin-built _driver Rust extension.
# Source: src/client.rs and src/async_bridge.rs. Regenerate via
# scripts/gen_driver_stub.py if you modify the pyo3 surface.

from collections.abc import Awaitable
from typing import Any

class RustAwaitable:
    def __await__(self) -> Any: ...
    def cancel(self) -> bool: ...

class RustValkeyDriver:
    @classmethod
    def connect_standard(
        cls,
        url: str,
        cache_max_size: int | None = None,
        cache_ttl_secs: int | None = None,
        ssl_ca_certs: str | None = None,
        ssl_certfile: str | None = None,
        ssl_keyfile: str | None = None,
    ) -> RustValkeyDriver: ...
    @classmethod
    def connect_cluster(
        cls,
        urls: list[str],
        ssl_ca_certs: str | None = None,
        ssl_certfile: str | None = None,
        ssl_keyfile: str | None = None,
    ) -> RustValkeyDriver: ...
    @classmethod
    def connect_sentinel(
        cls,
        sentinel_urls: list[str],
        service_name: str,
        db: int,
        cache_max_size: int | None = None,
        cache_ttl_secs: int | None = None,
        ssl_ca_certs: str | None = None,
        ssl_certfile: str | None = None,
        ssl_keyfile: str | None = None,
    ) -> RustValkeyDriver: ...
    def cache_statistics(self) -> tuple[int, int, int] | None: ...
    def get(self, key: str) -> Awaitable[Any]: ...
    def get_sync(self, key: str) -> Any: ...
    def set(self, key: str, value: bytes, ttl: int | None = None) -> Awaitable[Any]: ...
    def set_sync(self, key: str, value: bytes, ttl: int | None = None) -> None: ...
    def set_nx(self, key: str, value: bytes, ttl: int | None = None) -> Awaitable[Any]: ...
    def set_nx_sync(self, key: str, value: bytes, ttl: int | None = None) -> bool: ...
    def delete(self, key: str) -> Awaitable[Any]: ...
    def delete_sync(self, key: str) -> int: ...
    def delete_many(self, keys: list[str]) -> Awaitable[Any]: ...
    def delete_many_sync(self, keys: list[str]) -> int: ...
    def mget(self, keys: list[str]) -> Awaitable[Any]: ...
    def mget_sync(self, keys: list[str]) -> Any: ...
    def pipeline_set(self, entries: list[tuple[str, bytes]], ttl: int | None = None) -> Awaitable[Any]: ...
    def pipeline_set_sync(self, entries: list[tuple[str, bytes]], ttl: int | None = None) -> None: ...
    def incr_by(self, key: str, delta: int) -> Awaitable[Any]: ...
    def incr_by_sync(self, key: str, delta: int) -> int: ...
    def exists(self, key: str) -> Awaitable[Any]: ...
    def exists_sync(self, key: str) -> bool: ...
    def expire(self, key: str, seconds: int) -> Awaitable[Any]: ...
    def expire_sync(self, key: str, seconds: int) -> bool: ...
    def persist(self, key: str) -> Awaitable[Any]: ...
    def persist_sync(self, key: str) -> bool: ...
    def ttl(self, key: str) -> Awaitable[Any]: ...
    def ttl_sync(self, key: str) -> int: ...
    def pttl(self, key: str) -> Awaitable[Any]: ...
    def pttl_sync(self, key: str) -> int: ...
    def flushdb(self) -> Awaitable[Any]: ...
    def flushdb_sync(self) -> None: ...
    def keys(self, pattern: str) -> Awaitable[Any]: ...
    def keys_sync(self, pattern: str) -> Any: ...
    def type(self, key: str) -> Awaitable[Any]: ...
    def type_sync(self, key: str) -> str: ...
    def scan(self, pattern: str, count: int) -> Awaitable[Any]: ...
    def scan_sync(self, pattern: str, count: int) -> Any: ...
    def dbsize(self) -> Awaitable[Any]: ...
    def dbsize_sync(self) -> int: ...
    def info(self) -> Awaitable[Any]: ...
    def info_sync(self) -> Any: ...
    def client_list(self) -> Awaitable[Any]: ...
    def client_list_sync(self) -> Any: ...
    def config_get(self, parameter: str) -> Awaitable[Any]: ...
    def config_get_sync(self, parameter: str) -> Any: ...
    def object_encoding(self, key: str) -> Awaitable[Any]: ...
    def object_encoding_sync(self, key: str) -> str | None: ...
    def object_idletime(self, key: str) -> Awaitable[Any]: ...
    def object_idletime_sync(self, key: str) -> int | None: ...
    def memory_usage(self, key: str) -> Awaitable[Any]: ...
    def memory_usage_sync(self, key: str) -> int | None: ...
    def lock_acquire(self, key: str, token: str, timeout_ms: int | None = None) -> Awaitable[Any]: ...
    def lock_acquire_sync(self, key: str, token: str, timeout_ms: int | None = None) -> bool: ...
    def lock_release(self, key: str, token: str) -> Awaitable[Any]: ...
    def lock_release_sync(self, key: str, token: str) -> int: ...
    def lock_extend(self, key: str, token: str, additional_ms: int) -> Awaitable[Any]: ...
    def lock_extend_sync(self, key: str, token: str, additional_ms: int) -> int: ...
    def eval(self, script: str, keys: list[str], args: list[bytes]) -> Awaitable[Any]: ...
    def eval_sync(self, script: str, keys: list[str], args: list[bytes]) -> Any: ...
    def evalsha(self, sha: str, keys: list[str], args: list[bytes]) -> Awaitable[Any]: ...
    def evalsha_sync(self, sha: str, keys: list[str], args: list[bytes]) -> Any: ...
    def script_load(self, script: str) -> Awaitable[Any]: ...
    def script_load_sync(self, script: str) -> str: ...
    def script_exists(self, sha: str) -> Awaitable[Any]: ...
    def script_exists_sync(self, sha: str) -> bool: ...
    def pipeline_exec(self, commands: list[tuple[str, list[bytes]]], transaction: bool = False) -> Awaitable[Any]: ...
    def pipeline_exec_sync(self, commands: list[tuple[str, list[bytes]]], transaction: bool = False) -> Any: ...
    def lpush(self, key: str, values: list[bytes]) -> Awaitable[Any]: ...
    def lpush_sync(self, key: str, values: list[bytes]) -> int: ...
    def rpush(self, key: str, values: list[bytes]) -> Awaitable[Any]: ...
    def rpush_sync(self, key: str, values: list[bytes]) -> int: ...
    def lpop(self, key: str) -> Awaitable[Any]: ...
    def lpop_sync(self, key: str) -> Any: ...
    def rpop(self, key: str) -> Awaitable[Any]: ...
    def rpop_sync(self, key: str) -> Any: ...
    def lrange(self, key: str, start: int, stop: int) -> Awaitable[Any]: ...
    def lrange_sync(self, key: str, start: int, stop: int) -> Any: ...
    def llen(self, key: str) -> Awaitable[Any]: ...
    def llen_sync(self, key: str) -> int: ...
    def lrem(self, key: str, count: int, value: bytes) -> Awaitable[Any]: ...
    def lrem_sync(self, key: str, count: int, value: bytes) -> int: ...
    def lindex(self, key: str, index: int) -> Awaitable[Any]: ...
    def lindex_sync(self, key: str, index: int) -> Any: ...
    def lset(self, key: str, index: int, value: bytes) -> Awaitable[Any]: ...
    def lset_sync(self, key: str, index: int, value: bytes) -> None: ...
    def linsert(self, key: str, before: bool, pivot: bytes, value: bytes) -> Awaitable[Any]: ...
    def linsert_sync(self, key: str, before: bool, pivot: bytes, value: bytes) -> int: ...
    def ltrim(self, key: str, start: int, stop: int) -> Awaitable[Any]: ...
    def ltrim_sync(self, key: str, start: int, stop: int) -> None: ...
    def blmove(self, source: str, destination: str, wherefrom: str, whereto: str, timeout: float) -> Awaitable[Any]: ...
    def blmove_sync(self, source: str, destination: str, wherefrom: str, whereto: str, timeout: float) -> Any: ...
    def blmpop(self, timeout: float, keys: list[str], direction: str, count: int) -> Awaitable[Any]: ...
    def blmpop_sync(self, timeout: float, keys: list[str], direction: str, count: int) -> Any: ...
    def hget(self, key: str, field: str) -> Awaitable[Any]: ...
    def hget_sync(self, key: str, field: str) -> Any: ...
    def hset(self, key: str, field: str, value: bytes) -> Awaitable[Any]: ...
    def hset_sync(self, key: str, field: str, value: bytes) -> int: ...
    def hgetall(self, key: str) -> Awaitable[Any]: ...
    def hgetall_sync(self, key: str) -> Any: ...
    def hdel(self, key: str, fields: list[str]) -> Awaitable[Any]: ...
    def hdel_sync(self, key: str, fields: list[str]) -> int: ...
    def hincrby(self, key: str, field: str, delta: int) -> Awaitable[Any]: ...
    def hincrby_sync(self, key: str, field: str, delta: int) -> int: ...
    def hkeys(self, key: str) -> Awaitable[Any]: ...
    def hkeys_sync(self, key: str) -> Any: ...
    def hvals(self, key: str) -> Awaitable[Any]: ...
    def hvals_sync(self, key: str) -> Any: ...
    def hexists(self, key: str, field: str) -> Awaitable[Any]: ...
    def hexists_sync(self, key: str, field: str) -> bool: ...
    def hlen(self, key: str) -> Awaitable[Any]: ...
    def hlen_sync(self, key: str) -> int: ...
    def hmget(self, key: str, fields: list[str]) -> Awaitable[Any]: ...
    def hmget_sync(self, key: str, fields: list[str]) -> Any: ...
    def hmset(self, key: str, fields: list[tuple[str, bytes]]) -> Awaitable[Any]: ...
    def hmset_sync(self, key: str, fields: list[tuple[str, bytes]]) -> None: ...
    def sadd(self, key: str, members: list[bytes]) -> Awaitable[Any]: ...
    def sadd_sync(self, key: str, members: list[bytes]) -> int: ...
    def srem(self, key: str, members: list[bytes]) -> Awaitable[Any]: ...
    def srem_sync(self, key: str, members: list[bytes]) -> int: ...
    def smembers(self, key: str) -> Awaitable[Any]: ...
    def smembers_sync(self, key: str) -> Any: ...
    def sismember(self, key: str, member: bytes) -> Awaitable[Any]: ...
    def sismember_sync(self, key: str, member: bytes) -> bool: ...
    def scard(self, key: str) -> Awaitable[Any]: ...
    def scard_sync(self, key: str) -> int: ...
    def sinter(self, keys: list[str]) -> Awaitable[Any]: ...
    def sinter_sync(self, keys: list[str]) -> Any: ...
    def sunion(self, keys: list[str]) -> Awaitable[Any]: ...
    def sunion_sync(self, keys: list[str]) -> Any: ...
    def sdiff(self, keys: list[str]) -> Awaitable[Any]: ...
    def sdiff_sync(self, keys: list[str]) -> Any: ...
    def zadd(self, key: str, members: list[tuple[bytes, float]]) -> Awaitable[Any]: ...
    def zadd_sync(self, key: str, members: list[tuple[bytes, float]]) -> int: ...
    def zrem(self, key: str, members: list[bytes]) -> Awaitable[Any]: ...
    def zrem_sync(self, key: str, members: list[bytes]) -> int: ...
    def zrange(self, key: str, start: int, stop: int, with_scores: bool = False) -> Awaitable[Any]: ...
    def zrange_sync(self, key: str, start: int, stop: int, with_scores: bool = False) -> Any: ...
    def zrangebyscore(self, key: str, min: str, max: str, with_scores: bool = False) -> Awaitable[Any]: ...
    def zrangebyscore_sync(self, key: str, min: str, max: str, with_scores: bool = False) -> Any: ...
    def zrevrange(self, key: str, start: int, stop: int, with_scores: bool = False) -> Awaitable[Any]: ...
    def zrevrange_sync(self, key: str, start: int, stop: int, with_scores: bool = False) -> Any: ...
    def zincrby(self, key: str, member: bytes, delta: float) -> Awaitable[Any]: ...
    def zincrby_sync(self, key: str, member: bytes, delta: float) -> float: ...
    def zcard(self, key: str) -> Awaitable[Any]: ...
    def zcard_sync(self, key: str) -> int: ...
    def zscore(self, key: str, member: bytes) -> Awaitable[Any]: ...
    def zscore_sync(self, key: str, member: bytes) -> float | None: ...
    def zrank(self, key: str, member: bytes) -> Awaitable[Any]: ...
    def zrank_sync(self, key: str, member: bytes) -> int | None: ...
    def zcount(self, key: str, min: str, max: str) -> Awaitable[Any]: ...
    def zcount_sync(self, key: str, min: str, max: str) -> int: ...
    def zpopmin(self, key: str, count: int = 1) -> Awaitable[Any]: ...
    def zpopmin_sync(self, key: str, count: int = 1) -> Any: ...
    def zpopmax(self, key: str, count: int = 1) -> Awaitable[Any]: ...
    def zpopmax_sync(self, key: str, count: int = 1) -> Any: ...
    def xadd(self, key: str, id: str, fields: list[tuple[str, bytes]]) -> Awaitable[Any]: ...
    def xadd_sync(self, key: str, id: str, fields: list[tuple[str, bytes]]) -> str: ...
    def xlen(self, key: str) -> Awaitable[Any]: ...
    def xlen_sync(self, key: str) -> int: ...
    def xrange(self, key: str, start: str, end: str, count: int | None = None) -> Awaitable[Any]: ...
    def xrange_sync(self, key: str, start: str, end: str, count: int | None = None) -> Any: ...
    def xread(self, keys: list[str], ids: list[str], count: int | None = None) -> Awaitable[Any]: ...
    def xread_sync(self, keys: list[str], ids: list[str], count: int | None = None) -> Any: ...
    def xreadgroup(
        self, group: str, consumer: str, keys: list[str], ids: list[str], count: int | None = None
    ) -> Awaitable[Any]: ...
    def xreadgroup_sync(
        self, group: str, consumer: str, keys: list[str], ids: list[str], count: int | None = None
    ) -> Any: ...
    def xack(self, key: str, group: str, ids: list[str]) -> Awaitable[Any]: ...
    def xack_sync(self, key: str, group: str, ids: list[str]) -> int: ...
    def xtrim(self, key: str, max_len: int, approximate: bool = False) -> Awaitable[Any]: ...
    def xtrim_sync(self, key: str, max_len: int, approximate: bool = False) -> int: ...
    def xgroup_create(self, key: str, group: str, id: str, mkstream: bool = False) -> Awaitable[Any]: ...
    def xgroup_create_sync(self, key: str, group: str, id: str, mkstream: bool = False) -> None: ...
    def xpending(self, key: str, group: str) -> Awaitable[Any]: ...
    def xpending_sync(self, key: str, group: str) -> Any: ...
    def xpending_range(
        self,
        key: str,
        group: str,
        start: str,
        end: str,
        count: int,
        consumer: str | None = None,
        idle: int | None = None,
    ) -> Awaitable[Any]: ...
    def xpending_range_sync(
        self,
        key: str,
        group: str,
        start: str,
        end: str,
        count: int,
        consumer: str | None = None,
        idle: int | None = None,
    ) -> Any: ...
    def xclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        ids: list[str],
        idle: int | None = None,
        time_ms: int | None = None,
        retrycount: int | None = None,
        force: bool = False,
        justid: bool = False,
    ) -> Awaitable[Any]: ...
    def xclaim_sync(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        ids: list[str],
        idle: int | None = None,
        time_ms: int | None = None,
        retrycount: int | None = None,
        force: bool = False,
        justid: bool = False,
    ) -> Any: ...
    def xautoclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        start: str,
        count: int | None = None,
        justid: bool = False,
    ) -> Awaitable[Any]: ...
    def xautoclaim_sync(
        self,
        key: str,
        group: str,
        consumer: str,
        min_idle_time: int,
        start: str,
        count: int | None = None,
        justid: bool = False,
    ) -> Any: ...

def _test_resolved_bytes(value: bytes) -> RustAwaitable: ...
def _test_resolved_none() -> RustAwaitable: ...
def _test_resolved_int(value: int) -> RustAwaitable: ...
def _test_delayed_bytes(value: bytes, delay_ms: int) -> RustAwaitable: ...
def _test_pending() -> RustAwaitable: ...
def _test_dropped() -> RustAwaitable: ...
def _test_error(message: str) -> RustAwaitable: ...
def _test_server_error(message: str) -> RustAwaitable: ...
